### ISSUE TITLE
Chobby makes infologs suck.

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Chobby#10]
When using chobby, infolog.txt contains **both** the infolog stuff from chobby as well as the infolog stuff from any games you launch, making it a serious pain to separate the debugging info meaningfully. (this might-should go upstream somewhere, but idk)

EDIT: it also prevents you from reading infolog as long as chobby is open.

**Comment by GoogleFrog** [comment]
Mostly fixed with the default-disabled sever logging.
