### ISSUE TITLE
Consider some way of specifying boxes

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#107]
There is a group of players who is interested in playing on closed servers with bots, but are having issues with bot starting  positions.
They would like a way to specify initial boxes for them.

Excerpt from email:

> 
> Thank you for your reply to answer your question the game scenario that me and my friends usually play is on the map salmon stream usually load six months into the game and then four of us will take the outside corners it used to be that the Bots would load seemingly randomly or closer to the center of the map if there are no boxes or you can place a box in the center of the maps for them to load into
> 
> I can respect it looks like you guys are doing a major overhaul on the game so I'm trying to be patient I guess I'm just concerned that some of the things that made the game most fun for us might be a lost along the way if I don't speak up and mention it

> Right but with four people playing it makes sense to have the players occupy the corners like I said I understand that your overhauling the game and it looks as though you probably not done yet I'm okay with being patient I just wanted to make sure that these things that make the game to pick really fun for my group don't get left behind thank you for constantly trying to make the game better

**Comment by GoogleFrog** [comment]
I think they want the ability to place bot start positions after the game loads and before it begins. AIs have an owner, when start boxes are disabled these players could gain a UI to override their start position.

**Comment by pooparew** [comment]
I am the person who started this conversation with someone at zero k. Ya rather before the game starts (many with box placement like before) or between start and launch with a user interface like already mentioned (maby click to place bot commanders spawn locations) having control over where the bots start is desirable. This is true for my group and I don't see a negative to it.

Actually the more I think about it the ability to place each individual. Starting location regardless of what team the bot is on would be what's Best in my opinion

**Comment by GoogleFrog** [comment]
AI start positions can now be selected arbitrarily, no other startbox changes are required.

https://github.com/ZeroK-RTS/Zero-K/commit/59f2ccca233beac00f19733bfecca56e365c037e
