### ISSUE TITLE
Icon height setting is not honored

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Chobby#11]
Every time you start a game with chobby, icon height (for units, a widget which I DISABLED, although that doesn't seem to mean anything anymore) is reset to the default of 151 (or whatever it's actually set to). Setting it to max value in game works, but the setting is reset every game. There's also a setting in chobby->settings->interface for it, which does exactly nothing.

**Comment by mtroyka** [comment]
After testing this seems to be an issue with ZK and not a lobby issue.

**Comment by mtroyka** [comment]
nvm it really is a chobby issue.

**Comment by GoogleFrog** [comment]
What is the widget that you disabled?

**Comment by mtroyka** [comment]
I think it was gui_icon_height or something like that.

**Comment by GoogleFrog** [comment]
That widget, if disabled, is irrelevant. Icon height is an engine setting.

**Comment by CrazyEddieTK** [comment]
Icon Distance is an engine setting. Icon Height is specific to the gui_iconheight.lua widget, which crudely overrides the normal engine handling of icon drawing distance.

I don't know why the icon height setting would even be visible if the widget is disabled.
