### ISSUE TITLE
Steam Overlay input dropped frequently

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Chobby#112]
Because Chobby runs at an intentionally reduced framerate, hitting the Steam Overlay hotkey only works if it is held across a new Chobby frame, so the inputs are often dropped if one presses it for less than ~200ms.

**Comment by Licho1** [comment]
Was it tested with steam capable chobby or with what? Chobby increases fps when input is detected.

**Comment by GoogleFrog** [comment]
What is the steam overlay hotkey?

**Comment by Licho1** [comment]
Tested this, opening works, but closing fails if its held for short time.
Key is shift+tab.
Issue is FPS is increased when overlay is active. When this is done it should fix itself.

**Comment by danjreyes** [comment]
I'm not sure if this is related, when the overlay is activated when in the menu the background blinks. This doesn't happen in game.

**Comment by Licho1** [comment]
Yes it is related, we nee to increase chobby FPS while the overlay is active.

**Comment by GoogleFrog** [comment]
I recall doing something related to this and it works for me now.
