### ISSUE TITLE
Investigate team problem in missione

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#119]
See http://zero-k.info/Missions/Detail/226#169996

Somehow I ended up allied with the wrong team or the units were spawned for the wrong team.

**Comment by KingRaptor** [comment]
I suspect this is a product of ZeroK-RTS/Zero-K-Infrastructure/issues/1428

**Comment by GoogleFrog** [comment]
Likely fixed.
