### ISSUE TITLE
With default configs hold left to terraform does not work

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#122]
REpro:
- delete all configs
- pick startlight
- hole mouse on some uneven terrain (expecting to offer to flatten and raise)

-> nothing happens.

**Comment by GoogleFrog** [comment]
Intentional zero-k.info/Forum/Thread/23572

**Comment by Licho1** [comment]
Sorry, but this is obscure BS, i could not get it right even after watching video. Revert this please.

**Comment by Licho1** [comment]
How can you even be serious about this??
It is a pretty vital/important/strong feature and you hide it behind a keybind??

Game should be playable without keyboard, you cannot expect people to use it. And people who know it have massive advantage in just the ability of placing stuff on uneven terrain (don't even need spires).

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/0d5aeab0aaf079bc4f5fb7560043119bd8bbaab8
