### ISSUE TITLE
Default settings - ZK water invisible

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#123]
http://i.imgur.com/FtZDRI4.jpg

looks odd, look at hrash edges and shadows.
Also map trees meh:

http://i.imgur.com/NZJXTaK.jpg

**Comment by GoogleFrog** [comment]
Map??

**Comment by Licho1** [comment]
Any map, calamity 1.1 too.
Water missing.
Clean steam install.
