### ISSUE TITLE
Loading replays takes multiple minutes

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#136]
And then only shows the first 100 or so. Is there maybe some unneeded loop going through all replays? It seems to be CPU/Lua bottlenecked.

Low priority as it'll take some time for steamers to collect 10k+ replays. Yet this is still happening on raided SSDs, so I'm kinda sad :(

**Comment by GoogleFrog** [comment]
Does the lobby freeze while loading the replays?

**Comment by DeinFreund** [comment]
No, that has been fixed. At least for me.

Alcur reported a freeze though, ask him for details about that.
