### ISSUE TITLE
Modify data sent with Login to ZKLS

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#140]
When sending  SteamToken, do not send Login name
When sending Login name, do not send SteamToken UNLESS you want to link accounts.

Link steam to a different account will fail (only first link will work).

**Comment by GoogleFrog** [comment]
I have no way to test linking.

**Comment by Licho1** [comment]
Deleted all steamids from test server so you can test happily. 
Once.

**Comment by GoogleFrog** [comment]
There is no response code for "Link steam to a different account will fail". Add one.

**Comment by Licho1** [comment]
added             [Description("your steam account is already linked to a different account")]
            SteamLinkedToDifferentAccount = 8
