### ISSUE TITLE
Chobby should leave Post game chat after a new game starts or immediately after it ends

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Chobby#141]
This should prevent people from sending chat messages to the old post game chat, in the small period of time after their game ended and before springie registered that (during which time the player is still in the post-game chat of the previous game).

**Comment by DeinFreund** [comment]
I'd prefer them moving to a chat window. Sometimes after an interesting game you wanna keep discussing balance or strategies, even when you're already playing other games in the meantime.

The window in the MM tab should definitely be closed after starting a new MM game though.

**Comment by gajop** [comment]
This report is basically about your 2nd paragraph. I don't know about moving it to channels or not, or what should be the default setting
