### ISSUE TITLE
Chobby needs to use "best of" elos to properly show rank

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#144]
Alternative is that site sends icon name directly for simplicity (to ingame too).
Would you prefer that?

**Comment by Licho1** [comment]
Nevermind, don't do best off.
Current plan is:
- calculate percentiles
- base ranks on percentiles (will solve possible scoring mismatch between mm and teams)
- server sends final percentile and rank icon name to ingame and chobby

Just need to specify percentile based brackets.

**Comment by GoogleFrog** [comment]
I think chobby is correctly displaying rank.
