### ISSUE TITLE
There should be an indiciation that party invite is sent in the friend list

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#145]
Show for example little progressbar under player name to show if it has timed out or not.

**Comment by GoogleFrog** [comment]
Players with pending party invites have a blue symbol next to their name. Reopen if the symbol is missing.

**Comment by Licho1** [comment]
Ok i didnt see it in the friend list.

**Comment by GoogleFrog** [comment]
Is it missing there? Reopen and rename if it is missing in the friendlist.

**Comment by Licho1** [comment]
Yes it is missing from friend list
