### ISSUE TITLE
Added StartNewSpring for different engine demo replay

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#154]
Wire it as needed.
Also allows general different engine starting, like joining a game on different engine should be trivial with it.

**Comment by GoogleFrog** [comment]
See https://github.com/ZeroK-RTS/Chobby/commit/ef9dbf1621372dceb86682674f869b4975aa6151

**Comment by GoogleFrog** [comment]
Different engine replays work.
