### ISSUE TITLE
Please use full URLs when closing issues in commits

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Chobby#157]
Instead of writing `fixes #issuenumber`, try to write `fixes https://github.com/ZeroK-RTS/Chobby/issues/$issuenumber`. This will prevent incorrect issues being closed when merging upstream.
Probably most relevant to @KingRaptor  and @GoogleFrog

**Comment by sprunk** [comment]
Technically this is perpetually relevant, but the ticket is not doing any good being open but buried on page 13 of the ticket list.

**Comment by GoogleFrog** [comment]
I have been doing this for chobby. But I also doubt we are ever going to merge upstream in a git-officiated way.
