### ISSUE TITLE
Display factory exit (as an arrow)

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Chobby#159]
Currently it's easy to place factories in an undesirable way, especially for those like hover.
It would help if the exit was displayed before placement, preferably as an arrow.

Additionally it would be nice if we could rotate factory orientation by holding the mouse button. I think it's more intuitive than the keybindings. (see this ancient video as example: https://youtu.be/cu3Gi77nt_c?t=24 - although ZK probably only wants to use 4-sides)

**Comment by Licho1** [comment]
Widget already exists for that (and was in ZK at one time).

**Comment by gajop** [comment]
I'm aware BA(R) has it, but I never saw the default ZK with it (which I think it should). Any reason it shouldn't be in by default?

**Comment by gajop** [comment]
I've no idea why I create the issue in this repository. Closing
