### ISSUE TITLE
Change chobby to work with new protocol

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#16]
- [x] stop sending/expecting Ping messages
- [x] use PlayerCount value from BattleHeader (instead of counting people you know to be in battle)
- [x] after you receive JoinedBattle for yourself, internally (in chobby state) clear list of players in that battle
- [x] make sure nothing breaks if players chat in a channel but they are not visible in that channel (#zk). (Do not expect all User structures to be sent upon connecting)
- [x] use PlayerCount value from BattleHeader (instead of counting people you know to be in battle)

Optional:

- [x] make use of BattleID on User
- [ ] make use of PlayerCount on MessageHeader (sent on joined)

**Comment by GoogleFrog** [comment]
I dislike the JoinedBattle change. It feels like a magic global variable. I would rather that the server can optionally send a list of users as a key to JoinedBattle which is intended to replace the users thought to be in the battle.

**Comment by Licho1** [comment]
JoinedBattle is sent for other users joining other battles too (for example your friends, even if there is also User structure change).
I think it makes no sense to add list to that (without doing other changes)

**Comment by GoogleFrog** [comment]
Then don't send a list when other players join battles.

**Comment by Licho1** [comment]
yes but dont you think its ugly? Imo if we want to change it, there should be specific command "JoinBattleResponse"  or something like that

**Comment by Licho1** [comment]
Oh also added this:
- [ ] use PlayerCount value from BattleHeader (instead of counting people you know to be in battle)

At any moment you should know pretty accurate player count of eveyr battle, but you will likely know only about friends in those battles.

**Comment by GoogleFrog** [comment]
It is ugly. JoinBattleResponse is a better solution.

**Comment by GoogleFrog** [comment]
How do I know whether to send ping messages?

**Comment by GoogleFrog** [comment]
I don't know what use you want to made out of battleID.

**Comment by Licho1** [comment]
Me  neither, remember, you asked me to add it.. We could remove playerjoined/left otherwise no idea.

**Comment by GoogleFrog** [comment]
I think this is the last thing required to fix offline players: https://github.com/Spring-Chobby/Chobby/commit/d67016632aa333c1f0a9f9c645d4f6f03f677177

**Comment by Licho1** [comment]
Ok, I made changes as requested.
There is now BattleJoinSuccess which sends full list of players, bots and modoptions upon joining.
There is also BattleLeaveSuccess for leaving.

[b]Old commands for player joining/leaving battles were removed.[/b]

Use BattleID property on User instead to associate people with battles. Person can arrive before battle so expect that.

After one person sees other, he will continue receiving updates of that User until logout, which should make stuff more error-prone.

**Comment by GoogleFrog** [comment]
What do mean that a person can arrive before battle?

**Comment by Licho1** [comment]
User structure can send you battleid before battle with such id is known. If that is a problem I can address that.

**Comment by GoogleFrog** [comment]
I'd prefer the server did not send battleIDs for unknown battles.

**Comment by GoogleFrog** [comment]
> Old commands for player joining/leaving battles were removed.

I want them to be unremoved. You don't send every key on every User so how am I supposed to know when to make the user leave the battle? Which battle should it leave?

**Comment by Licho1** [comment]
Player count is now shown properly closing
