### ISSUE TITLE
Chobby gives incorrect error message when username/pw combination is wrong

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Chobby#162]
See http://zero-k.info/Forum/Post/171649#171649 . It has nothing to do with Steam as it's incorrectly shown to the user.

**Comment by GoogleFrog** [comment]
Get his infolog when he attempts to log in.

**Comment by gajop** [comment]
May need to ask him to do it again, as he got it working:
```
LocBoogieman - Today at 10:00 AM
when i went to the login it says Steam account not yet linked. re-register
when i try to register it says already registered, use password
i went online and reset the password
then try to login online and it says "invalid login name"
came right from my home page
ok i think i got it fixed here
the login is case sensitive and the c in my name is upper case unlike what i use most places
man im sorry about the fuss
and appreciate your time
it would be good if the error message differentiated clearly if wrong name or password
8)
NightwatchBOT - Today at 10:08 AM
<LoCBoogieman> great
<LoCBoogieman> i got it working
```

**Comment by GoogleFrog** [comment]
I would like to know whether he saw the steam login screen or the non-steam login screen. The non-steam login screen had tabs 'login' and 'register' and shows up whenever you attempt to log in. The steam screen does not appear when you log out then in again, it just automatically logs you in.

**Comment by GoogleFrog** [comment]
Reproduced, see https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1540
