### ISSUE TITLE
Can new players actually start and use chobby?

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#163]
http://i.imgur.com/lx3VBAl.png

**Comment by Anarchid** [comment]
I tested on a fresh system (win10, zk never previously installed, smurf steam account). Chobby worked fine, i played the UI tutorial before successfully registering a smurf and joining MP.

**Comment by quantumv** [comment]
Anarchid, thanks for testing. It could still be a design issue.

 For a start, we should request that the players type their password twice when registering. We could also add a caps lock warning.

**Comment by gajop** [comment]
Agree on that, but the bigger issue (imo) is case-sensitive username

**Comment by quantumv** [comment]
Woah, looks like something is really wrong. Only 15% of first-time users register.
Another 6% already have an account. This leaves 78% of players behind, at their first session.

![chrome_2017-03-02_20-21-23](https://cloud.githubusercontent.com/assets/49084/23523125/f15f80b6-ff85-11e6-827b-e4da4a2115f5.png)

![chrome_2017-03-02_20-28-52](https://cloud.githubusercontent.com/assets/49084/23523369/e302948a-ff86-11e6-953d-0cf1e1b8dd55.png)

Could also be a problem with our events.

**Comment by Licho1** [comment]
Well we know that only like 20% ever try MP so i think its real. It match server data about MP games.

**Comment by GoogleFrog** [comment]
GA catchs clicks on the MP or chat tabs and these are two of the three ways to register.

**Comment by quantumv** [comment]
Oh! That should help! Thanks for the analytics widgets btw GoogleFrog! Am using them as templates to wire more events!

**Comment by GoogleFrog** [comment]
New players seem to exist. GA tracks them.
