### ISSUE TITLE
Chobby turn whitescreen on minimized

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Chobby#165]
Chobby turn white screen after 1 sec of minimized

on AMD graphic card lastest driver
win 10

was unable to reproduce on my 2nd computer
was unable to reproduce by other players so far

https://youtu.be/SUsoNKLbvXg

**Comment by gajop** [comment]
infolog please

**Comment by Sortale** [comment]
http://pastebin.com/Tmu5vRQt

infolog as requested.

Also note that if I leave chobby minimized for more than 1 minute then the UI comback again

**Comment by Sortale** [comment]
been fixed in lastest

**Comment by GoogleFrog** [comment]
Thanks for reporting back.
