### ISSUE TITLE
Chobby refused to let me join MM even though I have map

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Chobby#168]
I cannot join MM, chobby said I do not have map even though I do

have restarted chobby, restarted PC

http://i.imgur.com/Myi0flO.jpg

**Comment by GoogleFrog** [comment]
I wouldn't trust the download screen. Check your maps folder.

**Comment by Sortale** [comment]
map folder said I have the map

**Comment by Licho1** [comment]
Delete them and wait for redownload. Possibly corrupted. I'm not sure rapid uses checksum, wrapper downloader does.

**Comment by Sortale** [comment]
delete them seem to work, thank you

 is there going to be a general solution for corrupted map file or we just gonna cross our finger and hope it doesn't happen?

**Comment by GoogleFrog** [comment]
The general solution for corrupted map file for MM maps is that steam will download those maps and presumably does a check. For other maps/distributions we have:
 * Fix the downloader system included in Spring (PR downloader, uses Spring infra).
 * Use wrapper download as it checks hashes.

**Comment by GoogleFrog** [comment]
Another 'solution' is to add a 'retry' button in the download screen which would delete the map file.
