### ISSUE TITLE
Investigate input offset on Anarchid hardware

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#17]
Someone needs to get on Anarchids computer and try to codify/investigate the /fullscreen /fullscreen workaround which fixes his input issues.

**Comment by Anarchid** [comment]
Duplicate of https://github.com/ZeroK-RTS/Chobby/issues/17

**Comment by Anarchid** [comment]
Also https://github.com/ZeroK-RTS/Chobby/issues/52

**Comment by sprunk** [comment]
Duplicate of https://github.com/Spring-Chobby/Chobby/issues/354
