### ISSUE TITLE
Chobby starts borderless in the expected windowed position

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Chobby#171]
Something either to do with engine 103.0.1-691 or Chobby changes between Feb 27th and March 4th 2017 made Chobby start in a small borderless window, rather than a proper window, when it is set to windowed and the game is set to borderless. More testing will be done on different settings pairs later, and setting Chobby to windowed after launching it makes it windowed as expected.

**Comment by GoogleFrog** [comment]
Impart IGL_data. I expect you to have BorderlessWindowed in game_settings. This has since been fixed but it lives on in your settings.

**Comment by dvr333** [comment]
Okay, that seems to fix it, though it was what caused #86 to appear fixed,
