### ISSUE TITLE
Setting for nanospray rendering on Intel cards

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Chobby#172]
I've just found out that in the internals of the spring engine it's hardcoded that GLSL extension are disabled for Intel GPUs. Unless shaders are enforced in ```springsettings.cfg```.

My tests have shown that NanoSpray shader, previously broken on Intel, works just fine if the following setting is added into ```springsettings.cfg```:
 ```ForceShaders = 1```

I suggest Chobby includes this setting by default.

**Comment by gajop** [comment]
Sure. It's 2017 and everyone should be able to run shaders by now.
Let's try and see report when it fails?

**Comment by lhog** [comment]
Maybe we should also ping @ashdnazg that he removes this ancient nonsense from the engine.

**Comment by ashdnazg** [comment]
I wanted to but @rtri was against.

**Comment by GoogleFrog** [comment]
Make up a good name for the setting in the Graphics tab. Possibly put ForceShaders = 1 or 0 in the Compatibility Mode option.

**Comment by lhog** [comment]
@GoogleFrog, I think it should be in the config by default and only be disabled in case game crashes. Not familiar with Chobby, so don't know if it's applicable.

**Comment by gajop** [comment]
Putting it on by default is possible (and preferred, so we can collect crashes before Steam release). Just make sure it can be manually turned off in the settings, so players who crash can still play the game.

This is not very difficult, just change some things in settings and add a option in the menu.

**Comment by GoogleFrog** [comment]
Does ForceShaders still exist?

**Comment by lhog** [comment]
No, it was removed: https://github.com/spring/spring/commit/16b1fbcb86c1ce9cdd95a61d6274f95d6795d1a5
