### ISSUE TITLE
No sound for MM battle found...

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Chobby#174]
Is this because I have my lobby music turned off?

**Comment by gajop** [comment]
I have finally figured this out.
Apparently changing the sound in ZK itself will impact Chobby sounds as well, so reducing (or turning off) the general sound in ZK will completely mute notification sound.
I think general sounds should just be restored after the game ends.

**Comment by Licho1** [comment]
Or use wrapper notifications more..

**Comment by gajop** [comment]
I want to avoid using the wrapper for anything that can be done within Chobby, as relying on the wrapper makes Chobby only usable for ZK.
Ideally the wrapper should only do the following:
- Start/restart into different engines
- Crash handling
- Provide integration with third party platforms like Steam

Basically everything you implement in the ZK wrapper, I'll have to reimplement in Chobby or in a game-agnostic wrapper, doubling the work.

**Comment by Licho1** [comment]
Can you flash the window, make a system popup, show notification in steam?
This is exactly the thing that needs top priority notification through wrapper. Of course play sound too.

**Comment by gajop** [comment]
Nope, Chobby cannot. Flashing the window is something I want to add to the engine, because it matters for non-lobby things too. I'm not sure if I want system notifications popups, but it's not possible now anyway.

Steam notifications is something the wrapper should be used for, yes. And generally using the wrapper for things that aren't possible (require engine work) makes sense, at least as a temporary measure.


But anyway, lobby can and should still be handling all sound.

**Comment by GoogleFrog** [comment]
The lobby doesn't handle all sound, Spring handles sound. There is a longstanding bug which would make Spring play no sounds sometimes.

**Comment by Licho1** [comment]
If you cannot fix it reliably now, use wrapper notification. We need this working for steam, does not matter how.

**Comment by gajop** [comment]
I haven't seen this bug, but in any case, this has to do with changing the general sound in ZK, and it affecting the sound in the lobby afterwards (https://github.com/ZeroK-RTS/Chobby/issues/174#issuecomment-285953184). 
Just restoring the proper volumes, like https://springrts.com/wiki/Springsettings.cfg#snd_volmaster to what it was beforehand should fix the issue.

**Comment by Licho1** [comment]
I dont even think its a bug .. I NEVER had any sound warning when SpringConnect is received i think its missing from code simply.

**Comment by GoogleFrog** [comment]
The ticket is not about SpringConnect, it is about MM battle found.

**Comment by gajop** [comment]
Do you use ingame sound?

**Comment by Licho1** [comment]
Yes, i have lobby music to 0, music ingame to 0, tts to 50% and sounds in game on. But they also fail to work randomly, and sometimes only work if i am tabbed out from the window

**Comment by Licho1** [comment]
Pretty hacky.. imo you should invoke the wrapper notification too to start window flashing on taskbar until its in engine.

**Comment by gajop** [comment]
This already exists: `WG.WrapperLoopback.Alert("Match found")`. Is this not the wrapper notification you speak?
Regarding hackiness:
1. This is simple enough that it should work reliably, so I can test these claims of Spring engine bugs. It works for me so the issue is closed.
2. This will fail if there are two or more nearly-simultaneous "Match found" notifications. The second one might be more silent at the end, and it can change those two volumes to the higher level permanently. 
3. A reasonable addition to this is to set those two volumes before and after the game starts (basically set the old values when chobby closes, and chobby-specific overrides when it starts). In that case, the notification sounds won't work reliably while the game is running, including in skirmish. 
4. This will change the volume for all sounds in a short period of time, including music and battle. The increase/decrease could be controlled better (linear falloff, scaling other channels to compensate for master increase, conditional increase of master).
5. Maybe games shouldn't be changing the master volume so eagerly? (assuming they do)

**Comment by GoogleFrog** [comment]
I dislike you closing tickets on ZK within your giant chobby repo PR. Fixing minor things from this tracker is just going to create confusion and merge issues. I really don't want to have two repositories working at once! I've been treating the chobby repo as a backend fixes repository (chili framework etc..). If you're going to work on general stuff we need to figure something else out.

**Comment by gajop** [comment]
Right now it doesn't really matter to me where I commit. I've been working in the Spring-Chobby repository mostly as a courtesy to you so I don't interfere with your stabilization workflow, as I'm not aware when you plan on making stables.
Although, remind me why I am to be blamed for there being two repositories with two different issue trackers? 
PS: I've never considered the original chobby repo as a backend fixes repository. Further, I've only recently gotten push rights here, and I still consider this to be the ZK fork.
PS2: I have and will continue to work in the entirety of Chobby, although I don't plan to extensively focus on ZK-specific things outside of doing fixes and cleanup.

**Comment by GoogleFrog** [comment]
I'm not blaming you for there being two repos, just expressing that I don't want there to be two repos. I don't expect real forks to ever merge so I have been treating ZK and chobby as one repo. I don't want significant work in both repos because that brings them closer to being real forks.
