### ISSUE TITLE
Player tooltips are broken in chobby

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#182]
Nothing appears when hovering people

**Comment by GoogleFrog** [comment]
Works for me.

**Comment by Licho1** [comment]
This was replicated by fealthas too, it randomly happens and randomly fixes itself.

**Comment by Licho1** [comment]
When it's broken, no player tooltip works at all.

**Comment by gajop** [comment]
Infolog is required. Please post one when it happens.

**Comment by Licho1** [comment]
https://paste.ee/p/I1d85 infolog here

**Comment by GoogleFrog** [comment]
Fixed probably.
