### ISSUE TITLE
Steam chobby not working

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Chobby#206]
when try to run chobby from steam just come up with black screen window

infolog below 

http://pastebin.com/QxFzYiRX

**Comment by Sortale** [comment]
still not working

**Comment by Sortale** [comment]
Licho suspect it's a default setting thing in adjunct with ATI/AMD GPU

Copy setting from currently running Chobby fixed the problem

**Comment by Licho1** [comment]
Please post the working config file so that we can compare with defaults and hopefully find the issue

**Comment by Sortale** [comment]
lups.cfg

https://www.dropbox.com/s/1sqirwiw8pvep43/lups.cfg?dl=0

Springsetting.cfg

https://www.dropbox.com/s/v6nicsb18xuv4gr/springsettings.cfg?dl=0

**Comment by Sortale** [comment]
also Steam chobby do not remember/apply window/fullscreen setting
