### ISSUE TITLE
Steam overlay flickers for me

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Chobby#212]
Pressing Shift+Tab brings up the Steam overlay, but it flickers at least for me. I was in the lobby client view when I activated it.

**Comment by Licho1** [comment]
It happens because FPS is not increased yet, there is other ticket for steam integration to do this.

**Comment by Sgathec** [comment]
Oh. By the way, I launched Chobby directly instead of clicking on the one on Steam.
