### ISSUE TITLE
Tutorials would be more discoverable under "Tutorials"

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Chobby#215]
Perhaps tutorials would help new players better if they were navigated to by clicking on "Tutorials" after selecting "Singleplayer". This change would allow discovering them more readily.  Someone who is brand-new might not actively search for tutorials.

**Comment by Licho1** [comment]
I think its fine. Very few people play tutorials, very few actively look for them.
People expect them to be "in-game" and if they want to go to singleplayer they will inevitably find them there.

**Comment by Sgathec** [comment]
Really? Are there any surveys or other data? If an in-game tutorial is expected, then that should probably be available in my opinion.

**Comment by GoogleFrog** [comment]
I plan to have a "Tutorials" submenu once I know the set of tutorials that will exist. I wait because the submenu should be a better design than a simple list of missions.

**Comment by Licho1** [comment]
Yes there are surveys and data. 
While many people reach missions, most try something else than tutorial.
We can also check how many actually finish it

**Comment by GoogleFrog** [comment]
There is a tutorials submenu. The fact that few people start with tutorials is also fine because the first campaign mission has a quick tutorial which efficiently covers what the player needs to know. The tutorials in the submenu are more in-depth.
