### ISSUE TITLE
Use high resolution icons for new rank congratulation screen

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#217]
Currently 32x32 pixel images are scaled up and thus look completely blurry and washed out.

I'd recommend using the shaded high res icons for the rankup screen, they look much nicer:
https://github.com/ZeroK-RTS/Zero-K-Artwork/tree/master/eloRanks/shaded

**Comment by DeinFreund** [comment]
Also if I may suggest, remove the rank down screen. It made me very sad.

Negative feedback should be avoided.

**Comment by GoogleFrog** [comment]
Done.
