### ISSUE TITLE
Find settings that works for FeXoR

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#222]
Apparently ZKL safe mode worked. Safe mode is the setting set after spring crashes and you click "yes" to minimal. What where the settings? https://github.com/ZeroK-RTS/CrashReports/issues/596

**Comment by Licho1** [comment]
It's start spring with --safemode .. no settings.
This switch overrides lots of individual values and possibly does some things that aren't accessible through .cfg too. 
Need to check engine source. 
Run spring.exe --list-config-vars > out.txt  to get info about which normal settings it overrides.

**Comment by KingRaptor** [comment]
A list of settings is available on [SpringRTS wiki](https://springrts.com/wiki/Springsettings.cfg)

**Comment by Licho1** [comment]
This is not the full asnwer though, because apparently it works even without safe mode.. So we should probably compare default zkl with default chobby settings.

**Comment by GoogleFrog** [comment]
Engines have been updated, crashes are down. No feedback available here.
