### ISSUE TITLE
Planetwars - can't join defense of allied planet

### ISSUE THREAD

**Issue by Vistritium** [ZeroK-RTS/Chobby#235]
Dynasty has defense pact with federation.
Empire is attacking Federation.
I'm Dynasty and should be able to defend the planet.
http://prntscr.com/eut08w
There is option to join, but nothing happens when I click it.
Eventually I couldn't defend.

**Comment by Licho1** [comment]
Is it possible it was downloading the map?

**Comment by Vistritium** [comment]
I have this map (at least the map with the same name) and Anarchid has the same problem.

**Comment by Licho1** [comment]
cannot see any bug, need to re-test and check what lobyb does
