### ISSUE TITLE
Add "block party invite" from player.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#237]

**Comment by DeinFreund** [comment]
This should just be part of ignore. (Right click player -> Ignore)

**Comment by GoogleFrog** [comment]
It probably is, apparently that is too harsh though and someone wanted a separate setting.

**Comment by DeinFreund** [comment]
Imo, right click menu is already too complicated. If party invite spam is a serious issue, disallow more than K invites per hour or so.

**Comment by Licho1** [comment]
Imo it should not happen, ignore should be enoguh.
