### ISSUE TITLE
UI crash on PlanetWars screen

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Chobby#248]
From #zkdev chat:

> **SilentShadow**: Hello everyone. I get some weird error in Chobby: when I login and click "Multiplayer" -> "Planetwars", the Chobby's interface crashes. Should I put the log into pastebin?

Infolog: https://pastebin.com/GfJxpXU5

**Comment by KingRaptor** [comment]
Possible duplicate of #218

**Comment by GoogleFrog** [comment]
Looks already fixed to me.
