### ISSUE TITLE
"1v1 available" not displayed when "coop available" displayed

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#259]
It only seems to be that only one of the two is displayed, even if both are available at the same time.

**Comment by GoogleFrog** [comment]
I think 1v1 available has precedence over coop available.

**Comment by DeinFreund** [comment]
It should, but it doesn't. 

![itdoesnt](https://i.imgur.com/eUJiUk6.png)

**Comment by GoogleFrog** [comment]
Tested and I've found that the server sends incomplete information https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1759

**Comment by sprunk** [comment]
Fixed server side.

**Comment by DeinFreund** [comment]
I couldn't test in Chobby yet because of different engines on test server. The protocol messages are sent correctly now, listing all available queues.

**Comment by GoogleFrog** [comment]
Claim is that this is fixed.

**Comment by DeinFreund** [comment]
![bug](https://i.imgur.com/S2WfOgA.png)

Server sends correct information(coop and 1v1 instant start), only 1v1 is displayed. Is this intended behaviour?

**Comment by GoogleFrog** [comment]
There is only space for one. I ranked them according to rarity.

**Comment by DeinFreund** [comment]
I would prefer if this would scale with window size, but that's another issue.
