### ISSUE TITLE
Can't switch Zero-K as borderless window between monitors

### ISSUE THREAD

**Issue by Stuart1998** [ZeroK-RTS/Chobby#268]
See video https://youtu.be/RVmqr-Q-yXY

Applies in ZK in-game as well.

**Comment by GoogleFrog** [comment]
Lua has no way of seeing how many screens you have or the resolution of any screen other than your first. Automatic detection and screen selection sounds impossible from lua alone. See https://springrts.com/mantis/view.php?id=5613

I've added a new display type "Manual Borderless" which lets you input (x, y, width, height) manually. It can accommodate any desired screen setup.
