### ISSUE TITLE
Chobby resets window state after game finishes

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Chobby#270]
I run chobby in windowed mode, window is maximized before game start
For some weird reason after game finished window got resized to some weird size so I need to maximize it again
very annoying

**Comment by GoogleFrog** [comment]
Give screenshots of where the window is in both modes.

**Comment by GoogleFrog** [comment]
Cannot reproduce and fixed a possibly related issue. https://github.com/ZeroK-RTS/Chobby/commit/78fdcdf962a24fe812717e311cb41c4f61dbdb28

**Comment by let4be** [comment]
Just checked, bug still here
looks something like this after state reset
![wtf](http://i.imgur.com/2eydP3P.png)

**Comment by GoogleFrog** [comment]
Chobby isn't updated.

**Comment by let4be** [comment]
Seems to work fine for me
