### ISSUE TITLE
Everything is blurred after I maximized a window after watching a movie

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Chobby#272]
Blurred:
![nice bugs](http://i.imgur.com/nY6YxGL.png)

After restart of chobby:
![nice bugs](http://i.imgur.com/FkGJ0Yz.png)

What is going on?

**Comment by Licho1** [comment]
It does not seem to be blurred.. different brightness .. gamma maybe?

**Comment by let4be** [comment]
Yea, blurred is probably a wrong word but it's clearly looking weird
I did not change any settings - happened on its own

**Comment by DeinFreund** [comment]
I've had similar issues with Chobby/Spring screwing over Windows screen color calibration.

**Comment by springraaar** [comment]
Was the blur constant or flickering?

I've recently logged into ZK after not playing for a month or so and chobby's UI is all blurry and flickers, but the game itself works fine.

![blurry_shaky_chobby](https://user-images.githubusercontent.com/11828472/30769465-c65d7bb2-a010-11e7-820d-79170d79a2ab.jpg)

![blurry_shaky_chobby2](https://user-images.githubusercontent.com/11828472/30769460-a9bf9d00-a010-11e7-861a-c2485f1f607d.jpg)


infolog
https://pastebin.com/vdcgh3P5

**Comment by GoogleFrog** [comment]
Not related to the original ticket. It seems to be solved.
