### ISSUE TITLE
Permanent maximum CPU usage

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#276]
Infolog: http://paste.springfiles.com/view/ef3e0c65

With the new engine 103.0.1-1134-gbe1c786 Chobby permanently occupies one core at full load. Full Speed Draw Updates is disabled.

**Comment by GoogleFrog** [comment]
Cannot reproduce. Full speed updates was force-enabled in one version as a workaround so make sure you are up to date.
