### ISSUE TITLE
ZK(wrapper) chobby doesn't start for me anymore

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Chobby#278]
https://pastebin.com/uKTHrYRq

Haven't tried it in a while so I don't know how recent this is.

**Comment by Oflameo** [comment]
I had this issue too. I reported it in my last post in this thread https://github.com/ZeroK-RTS/Zero-K/issues/2340.

**Comment by gajop** [comment]
Really? Where is the report exactly? That thread seems to relate to engine/GPU memory requirements, and not the ZK chobby wrapper.

**Comment by Oflameo** [comment]
I have both an infolog and a drm report in my last comment. It did relate to my GPU and memory requirements when I was running Debian 8 when my PC hardware clearly exceeded the GPU and memory requirements. Now when I am on Debian 9 and and my PC hardware clearly exceeded the GPU and memory requirements the game and or lobby crashes. I am still trying to figure out some harebrained workaround so I can at least play again.

**Comment by gajop** [comment]
Yes I've seen them, and it has nothing to do with this issue.
The problem here is with the Chobby **wrapper**, the C# application used to start Chobby.
The problem is **not** with the engine/GPU or Chobby itself.

**Comment by Licho1** [comment]
Do you have mono-complete installed? It seems you are missing System.Numerics library from your mono, try checking how to get it for your OS.

**Comment by Oflameo** [comment]
I had mono complete installed.

`mono-complete/stable,now 4.6.2.7+dfsg-1 amd64 [installed]`

**Comment by Licho1** [comment]
It seems to be a mono bug, temporary fix is to switch json library version:
http://json.codeplex.com/workitem/24176

**Comment by gajop** [comment]
It might be an issue with my mono installation as I had to change the mono version on my system to mod for Rimworld - things seem unstable/broken-ish now so need a few days to reconfigure it (it's surprisingly difficult)

**Comment by Oflameo** [comment]
I am running this version which is part of Debian 9. `libmono-system-json4.0-cil/stable,now 4.6.2.7+dfsg-1 all [installed,automatic]
`

Which version should I switch to?

**Comment by gajop** [comment]
Sigh, why do you keep responding to this issue? You are not affected by this problem.

**Comment by gajop** [comment]
Yeah, this was due to the old mono being installed.
This shouldn't be an issue to any normal users, installing the old mono wasn't an easy experience in the first place.
