### ISSUE TITLE
Figure out the placement of missions

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#280]
The three featured tutorial missions are good. I would like to replace the Missions submenu with a Tutorials submenu that only contains these three missions. The chicken and fight vs CAI missions are replaced by the simple setup availible by default in skirmish. The sandbox is probably not required if we make Very Easy circuit actually very easy.

We've got some cool missions. I like Kodachi Rally, if it works could we use it as a campaign mission? Any other missions?

Input @KingRaptor, @Licho1?

**Comment by KingRaptor** [comment]
There's also Air Force Command, although it may be overly complex and it may be more desirable to just do one or more missions using the existing campaign mission system.

Can't think of any other Mission Editor missions I'd want to put in, although more could be made if so desired.

Unsure if I have any particular preference on putting things like Kodachi Rally in campaign (vs. having them in a list of "loose" missions).

**Comment by CrazyEddieTK** [comment]
I'll re-up my suggestion from https://github.com/ZeroK-RTS/Zero-K/issues/1806#issuecomment-296161765

>I think there's value in having the Sandbox -> 2v2 -> 2v1 -> 1v1 sequence presented to new users as an Official Thing You Can (And Probably Should) Do in the user interface, rather than leaving it to their own devices to discover via the skirmish interface.

**Comment by CrazyEddieTK** [comment]
Also, I think Chickens is sufficiently different from Skirmish that it should have its own submenu tab, probably labeled "Survival" (or something similar but with a different flavor, perhaps: "Onslaught" or "Invasion" or some such).

Chickens is a great feature of ZK; it deserves being highlighted as more than just an option under Skirmish.

**Comment by GoogleFrog** [comment]
I think Skirmish is a fairly standard term for what the submenu offers. 

> Skirmish mode
A gameplay mode in which players can fight immediate battles without having to go through the linear, story-based campaign mode. It is popular in real-time strategy games.

https://en.wikipedia.org/wiki/Skirmish_mode

![skirmishsearch](https://user-images.githubusercontent.com/1318249/27990810-0689c386-64a6-11e7-91af-e6859ed69581.jpg)

**Comment by CrazyEddieTK** [comment]
My main point was less about the term (although I did ask about it in the other ticket, so thanks) and more that we should encourage new players to play through a particular sequence of skirmishes in order to learn the game, as a kind of post-tutorial trainer.

**Comment by GoogleFrog** [comment]
I don't want to overload menus with too many submenus. I think 'Tutorials', as distinct from missions, is a vital submenu. Campaign, Skirmish and Load are also submenus and this is near the limit of what I think is reasonable.

I think sandbox is detrimental in its current form. Building all the units without doing anything with them can give you a sense that you have seen everything but what you have seen is mostly boring. There needs to be some goal or direction in the sandbox. It is much more interesting if there is a base to destroy and the occasional trivial attack.

The 2v1, 2v2 and 1v2 missions suffer from using CAI and their lack of difficulty settings. There will be a version of circuit which is significantly easier than CAI and creates an almost sandbox game. I agree that some sort of 2v1 progression is good but that it should be improved and placed in tutorials. Build options could be limited (at least for the AIs). There should be some sort of tutorial-ish setup at the start of a 2v1 mission that reminds the player to build a factory, some mexes and some energy.

Have you looked at the default skirmish menu recently? Chickens fits into the menu well alongside 1v1, 2v2 and 3v3.

**Comment by CrazyEddieTK** [comment]
> I think sandbox is detrimental in its current form. [etc]

True enough. I suggested https://github.com/ZeroK-RTS/Zero-K/issues/2242 and @db81 suggested https://github.com/ZeroK-RTS/Zero-K/issues/2179 . I think there's value in starting new players off in an environment where they can spend ten minutes figuring out how to walk their commander around and issue area attack commands without getting all their stuff blown up by the AI. But that also means they need something to shoot at.

> The 2v1, 2v2 and 1v2 missions suffer from using CAI and their lack of difficulty settings.
> I agree that some sort of 2v1 progression is good but that it should be improved and placed in tutorials.
> There should be some sort of tutorial-ish setup at the start of a 2v1 mission

Agreed. I don't mean to suggest that the specific 2v1 etc missions as they are now should be used; merely something like them. They should have the same kind of window dressing as the basic tutorials do, just not as much of it. Putting them with the basic tutorials would be a fine place for them to live, although perhaps within the tutorial tab there could be some further visual separation so that the difference between "basic tutorials that show you how to move the mouse" and "training sessions that pit you against easy opponents" is well delineated.

**Comment by GoogleFrog** [comment]
Pretty sure this is done.
