### ISSUE TITLE
Ugly loading of chobby

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Chobby#283]
![wtf](http://i.imgur.com/eVNyBT5.png)

I see this sh*t for like 2 seconds even with SSD
can we do something about it?

**Comment by GoogleFrog** [comment]
Not without an engine change. The screen occurs before anything that we have control over.

See https://springrts.com/mantis/view.php?id=5632

**Comment by gajop** [comment]
This is better than just freezing the application. I'm not sure how much can be changed engine-side easily, as you probably can't load the archive before VFS is initialized.

**Comment by GoogleFrog** [comment]
Engine should have a reasonably nice default screenshot and better text placement. Then I'd like it to read an image (configurable path in springsettings?) and display that instead of its screenshot.

**Comment by gajop** [comment]
That makes sense. Try to mantis is somewhere if you haven't already.

**Comment by Licho1** [comment]
There could be stuff that is not in VFS to be displayed..
for example "base load screen.png" in the data folder (and not in archives) .. engine could just show that.

**Comment by GoogleFrog** [comment]
Fixed with loadscreen.

**Comment by let4be** [comment]
I see exactly the same just in smaller white text in the bottom part of the window...
How is it fixed?...

**Comment by GoogleFrog** [comment]
There is also a splashscreen.

**Comment by let4be** [comment]
loading window still looks totally empty for me, just black empty window with that text
werent u going put some background image here or something?...

**Comment by GoogleFrog** [comment]
Are you running chobby in the standard way?

**Comment by let4be** [comment]
yea, just opening as I always did (installed from zero-k site)
But I did not do a fresh install, but it updated itself a couple of times

**Comment by GoogleFrog** [comment]
Do you have a folder called MenuLoadscreens and is anything in it?

**Comment by GoogleFrog** [comment]
Do you have MenuLoadscreens set as a config value for an appropriate looking key in springsettings?

**Comment by let4be** [comment]
C:\Users\dev\Documents\My Games\Zero-K\MenuLoadscreens
there is file loadscreen.png here

there is no mention of MenuLoadscreens in springsettings.cfg

I think I get it, I told chobby to use my custom springsettings.cfg, could it be because of it?
why do we store such config information in springsettings.cfg? isn't it supposed to be used for ingame-only configuration?

**Comment by let4be** [comment]
hrm, just tried unchecking "neuter settings" and it did not solve the problem

**Comment by gajop** [comment]
It's not possible to make it game-only as game archives are not yet loaded when that screen is displayed.

`I think I get it, I told chobby to use my custom springsettings.cfg, could it be because of it?`
Quite possibly. If settings were changed outside of Chobby, it kinda voids warranty imo.
Please try from a fresh install.

**Comment by let4be** [comment]
Thanks, will do

**Comment by GoogleFrog** [comment]
This will be your problem: https://github.com/ZeroK-RTS/Chobby/blob/master/LuaMenu/configs/gameConfig/zk/defaultSettings/springsettings.cfg#L60

With neuter settings disabled that key would have been added to your springsettings on the relevant update. It should be added once you restart chobby with neuter settings disabled.

**Comment by let4be** [comment]
adding this line manually fixed the problem
disabling neuter settings did not fix it automatically though...

**Comment by gajop** [comment]
Neuter settings not effective enough (make new issue?).
Perhaps it's not removing your old settings, such as the custom data dir (with custom spring settings). Or something.
