### ISSUE TITLE
Cannot minimize chobby window when playing game

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Chobby#284]
I have chobby set to use windowed mode(not borderless)
But I see NO regular minimize/maximize buttons and I see no regular window header when playing zk
When I quit a game back to chobby everything comes back to normal and I see window header

How do I bring back control over window?!....

**Comment by let4be** [comment]
Any advice? this is really annoying

**Comment by GoogleFrog** [comment]
This is an interesting ticket. In theory there is no difference between playing and not playing. What happens if you are playing, switch to borderless and then switch back to windowed?

**Comment by gajop** [comment]
It sounds to me he's using fullscreen or borderless for game window settings.

Windowed mode is probably just his lobby window settings.

**Comment by let4be** [comment]
Indeed it was the case. Seems like I couldn't find this option...

**Comment by gajop** [comment]
fwiw i think it's an unnecessary confusion to have two different settings for resolution. only power users care for it
