### ISSUE TITLE
Polish campaign UI

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#294]
The campaign UI needs some polish:
- [x] Make a decision about the technofluff that is displayed on the planet screen. The current proposal is 'Primary' and 'Type'.
- [x] Enlarge the mission description text and ensure it has enough space to be displayed. 
- [x] Make a fancy XP and level up animation for the victory screen.
- [x] Improve the loss screen.
- [x] Put something interesting in the top panel of the Commander tab. Display XP, level, possibly a picture of the commander, commander name and relevant statistics based on the equipped weapons (health, speed, dps..?).
- [x] Make the technology screen sorted into paragraphs with specified order.

**Comment by Aquanim** [comment]
Should the commander screen and a start battle screen be able to coexist?
Planet images should match the map which the battle is played on but this should wait until missions are finalised.
The Codex needs some fluff written for it but I'm not sure that's pertinent to this ticket.
