### ISSUE TITLE
Wire up wrapper loopback interface

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#3]
Interface is here
https://github.com/ZeroK-RTS/Chobby/blob/master/LuaMenu/widgets/zk_loopback.lua

Put widget to some WG stuff.

Connect:
- [x] on MM AreYouReady invoke Alert (flashes spring window)
- [x] on clicking hyperlink OpenUrl
- [x] clicking on self should visit own profile on website
- [x] optionally add a way/shortcut to browse maps, replays online
- [x] optionally open primary writable dir from settings (to hand edit configs, check infolog)

**Comment by GoogleFrog** [comment]
The interface is wired up but the wrapper appears to do nothing. https://github.com/ZeroK-RTS/Chobby/commit/ed553db5fcab5c0b4c1e7b807ec5488834846214

**Comment by Licho1** [comment]
I had tested it, please check that wrapper.
You can check logs. Unable to check it atm, chobby master wont connect to lobby server at all (stuck on connecting)

**Comment by GoogleFrog** [comment]
All done.
