### ISSUE TITLE
Sometimes changing settings fails, at least visually

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Chobby#301]
See https://github.com/ZeroK-RTS/Zero-K/issues/2470

>Selecting a setting sometimes works, sometimes doesn't. I'd say it has about 1/3 - 1/4 chance to work.
>
>https://youtu.be/-2oLAa3jVkM
>
>Using Arch Linux, GTX 1080 Ti with proprietary Nvidia drivers.

**Comment by GoogleFrog** [comment]
Cannot reproduce.

**Comment by C0rn3j** [comment]
@GoogleFrog Would be more helpful if you said which OS, GPU and driver version you used.

**Comment by GoogleFrog** [comment]
============== <User System> ==============
  Spring 103.0.1-1285-gd322668 develop
    Build Environment: boost-105500, GNU libstdc++ version 20130531
     Compiler Version: gcc-4.8.1
     Operating System: Microsoft Windows
Microsoft Business Edition, 64-bit (build 9200)
Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz; 16303MB RAM, 32687MB pagefile
     Binary Word Size: 32-bit emulated
     Deque Chunk Size: 128
        Process Clock: std::chrono::high_resolution_clock
   Physical CPU Cores: 6
    Logical CPU Cores: 12
============== </User System> ==============
[good_fpu_init] CPU SSE mask: 127, flags:
	SSE 1.0:  1,  SSE 2.0:  1
	SSE 3.0:  1, SSSE 3.0:  1
	SSE 4.1:  1,  SSE 4.2:  1
	SSE 4.0A: 0,  SSE 5.0A: 0
	using streflop SSE FP-math mode, CPU supports SSE instructions
[WatchDogInstall] Installed (HangTimeout: 5sec)
[WatchDog::RegisterThread] registering controls for thread [main]
[GL::CheckAvailableVideoModes] desktop={1920x1080x24bpp@60Hz} current={1920x1080x24bpp@60Hz}
	display=1 modes=32 bounds={x=0, y=0, w=1920, h=1080}
		[ 1] 1920x1080x24bpp@60Hz
		[ 2] 1680x1050x24bpp@60Hz
		[ 4] 1600x1024x24bpp@60Hz
		[ 6] 1600x900x24bpp@60Hz
		[16] 1280x800x24bpp@75Hz
		[20] 1280x720x24bpp@75Hz
	display=2 modes=36 bounds={x=1920, y=0, w=1920, h=1080}
		[ 1] 1920x1080x24bpp@60Hz
		[ 3] 1680x1050x24bpp@60Hz
		[ 5] 1600x1024x24bpp@60Hz
		[ 7] 1600x900x24bpp@60Hz
		[17] 1280x800x24bpp@75Hz
		[21] 1280x720x24bpp@75Hz
[GR::CreateSDLWindow] using 4x anti-aliasing and 24-bit depth-buffer (PF="SDL_PIXELFORMAT_RGB888")
[GR::LogVersionInfo]
	SDL version : 2.0.4 (linked) / 2.0.4 (compiled)
	GL version  : 4.5.0 NVIDIA 382.05
	GL vendor   : NVIDIA Corporation
	GL renderer : GeForce GTX 1060 6GB/PCIe/SSE2
	GLSL version: 4.50 NVIDIA
	GLEW version: 1.5.8
	GPU memory  : 6144MB (total) / 4374MB (available)
	SDL swap-int: 1

I don't expect to be able to fix it without reproducing.

**Comment by C0rn3j** [comment]
>I don't expect to be able to fix it without reproducing.

>>Operating System: Microsoft Windows
>>Microsoft Business Edition, 64-bit (build 9200)

Well there is a difference between using a bleeding edge Linux distribution versus outdated Windows.

Pretty sure that if you tried to reproduce it under Linux you'd be able to repro.

**Comment by GoogleFrog** [comment]
You know, I don't have to take this. I'm not going to install a different OS to fix this issue, and besides, the version failure is with Spring since windows reports it as 15063.540.

Try to determine whether the setting is applied when it visually fails to update. This should be made obvious by changing the menu display mode (or by changing game display mode while ingame).

**Comment by C0rn3j** [comment]
> I'm not going to install a different OS to fix this issue

And that's fine, nobody is forcing you, my point was that "can't reproduce" is useless if you don't even mention what environment you tested it on, and perhaps pointing out that you don't have a Linux box to test it on would be cool too.

>Try to determine whether the setting is applied when it visually fails to update.

Will try later.

**Comment by C0rn3j** [comment]
The setting is not applied at all. It's basically as if I didn't do anything.
