### ISSUE TITLE
Chobby does not properly assign players to battles upon connecting

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#31]
1) connect to zk server
2) hover battles with mouse, shows no players there, hover players they show ingame but no battle icon
3) check infolog, it shows that User had battleID set properly and was sent after BattleAdded

**Comment by GoogleFrog** [comment]
Fixed.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Chobby/commit/cde51cbdfcb418b2efd297e712ff60dba4bf4d93
