### ISSUE TITLE
After a successful !start, spectators are forced to start Spring

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Chobby#324]
Please add a checkbox for disabling the automatic game launch. Spectators may want to chat, observe the discussion or wait for a suitable player count or certain maps instead of watching the battle. This feature might slightly increase the amount of disruptive spectator chat, but I think that is not a reason to reject this request.

**Comment by gajop** [comment]
This option sounds to me like something only power users would want. Adding it to the GUI would just add clutter. I'd recommend moving it to the settings or allowing configuration through a config file.

**Comment by Licho1** [comment]
Clutter imo. If you just want to chat, why do you join in-game lobby? You could chat on discord.. and you can always just close game or just switch back to lobby while it is in progress

**Comment by Sgathec** [comment]
Some chat happens only in the room. 

When the game starts, the whole lobby client is disabled for a while.

**Comment by Licho1** [comment]
Isn't that an issue then? The lobby being unresponsibe during engine load?

**Comment by Sgathec** [comment]
Yes, I think so.

**Comment by gajop** [comment]
that's an entirely separate issue, no?
also, messages should still be received after loading is finished

**Comment by Sgathec** [comment]
Yes, it's a separate issue.

**Comment by Sgathec** [comment]
@mojjj has already submitted issue #60 to ask for the Chobby overlay while the game is loading.

**Comment by Gyslain** [comment]
I want this option too!
Why? Because, when I join a room, I don't want necessary to play the current map and/or to play with the current players pool. But I want to be sure to not miss what would be a good game for me (no speed metal with descent players for ex.).
Why is this request closed?
