### ISSUE TITLE
Mission 0 problems

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#328]
_(checklist is updated now. Still, you can view [this doc](https://docs.google.com/document/d/1dlXZyp97vV2H_Odb3LlDSuYTk1z_dGtPVSGT7eYNJ0U/edit?usp=sharing))_

Some general issues:
 - [x] The campaign main objectives screen appears as well as the mission objectives screen.
 - [x] The text in the objective window is too small.
 - [x] Reclaim and repair should be illegal throughout. Currently you can move your commander with area reclaim.
 - [x] Do not hide the resource bar. The tutorial makes no mention of it appearing so it will likely be completely ignored when it does appear. Regardless, the resource bar makes up the borders of the top left and top right UI on sufficiently small screens so removing the resource bar requires skinning support. I did not even notice that it was missing before I saw it on a small screen.
 - [x] Sometimes this mission will start with an empty integral menu. This seems to occur when it is first run. Integral menu starts enabled to allow for pregame queue. For campaign mission objectives I will look into overriding that behaviour, which should fix it.
 - [x] Check that the markers still work. I fixed some stupidness in the marker widget and don't know how to test mission with a dev version.

Objectives 1:
 - [x] The zoom in distance is too short. Players should zoom to a less close distance.
I think this is a fine distance:
![screen00506](https://user-images.githubusercontent.com/1318249/29748759-35be0d16-8b60-11e7-8a00-375c09179ea5.jpg)
 - [x] There is too much text.
 - [x] "Zoom the camera to your commander:\n + Pan the camera with arrow keys, the screen edge or middle mouse button.\n + Zoom with scrollwheel or page up and page down."
 - [x] Selecting the commander should be illegal during objective 1.

Objective 2:
 - [x] Too much text. "Select your commander by left clicking on it".
 - [x] There is no objective marker, what if I had zoomed to it then somehow lost control, I wouldn't know where the commander is. Perhaps use a small marker though. The marker could say "Left click to select".

Objective 3:
 - [x] Rephrase. "Right click on the ground to issue a move command. Move your commander to the location to the right.\n\nMake sure your commander is selected"
 - [x] I can give move orders anywhere. All move orders not near "Go here" should be illegal.
 - [x] Marker should read "Right click to move here".
 - [x] The commander takes a bit too long to walk. Perhaps start it 400 elmos to the right. Start Glaives 200 elmos to the right.
 - [x] The Glaives should not be visible before the objective, they are distracting. Move this entire objective 50 elmos to the right.

Objective 4:
 - [x] Could possible do with a marker on the screen to tell people what to do. "Select all your units".
 - [x] The label should say "Left click and drag to select all your units".
 - [x] The text should say "left clicking".
 - [x] All commands should be illegal during this objective to prevent people from selecting single units and moving them around.

Objective 5:
 - [x] Marker should say "Right click and drag from here..."
 - [x] This objective is bugged, for example it can be fulfilled without moving your commander.
 - [x] Remove the "select your units" + point.
 - [x] Add end paragraph "Make sure your units are selected".
 - [x] This objective should be about 60 elmos to the right, to compensate for the Glaives being moved.

Objective 6:
 - [x] Marker should say "Right click to attack", should probably be white for consistency.
 - [x] Move order should be illegal, it is not.
 - [x] Force fire on the ground should also be illegal.
 - [x] Replace the text with "Right click to attack and destroy the enemy Storage.
 - [x] Add "(Make sure all your units are selected)".

Objective 7:
 - [x] Mex construction on the wrong point is not illegal.
 - [x] Marker should say "Build a Metal Extractor"
 - [x] The instructions are confusing/wrong.
 - [x] The Marker text should be small.
 - [x] The last point should say "Left click on the metal spot".
 - [x] Always say 'metal spot' instead of 'mex spot'.
 - [x] Add "(Make sure your commander is selected)".

Objective 8:
 - [x] Mex construction is not illegal.
 - [x] Solar construction in a different location is not illegal.
 - [x] The suggested location for solar construction is on uneven terrain. Place it a little further from the mex.
 - [x] Place a marker "Build a Solar Collector". The marker currently says "Build a solar".
 - [x] Be consistent with mexes, the start text should be "Build a Solar Collector. This will supply energy needed for construction and ability upkeep.".
 - [x] Remove "(highlighted)".
 - [x] The bottom point should be "Left click on the ground to place the building"
 - [x] Add "(Make sure your commander is selected)".

Objective 9:
 - [x] Mex and Solar construction is not illegal.
 - [x] Factory construction in the wrong location (and facing) is not illegal.
 - [x] The tone is fluctuating around, now the objectives say "Lets make a factory to build units". I'd remove that line.
 - [x] Just say "Build a Cloaky Bot Factory".
 - [x] Remove "(highlighted)".
 - [x] The paragraph at the bottom should read "Tip: Rotate structures with left click and drag or with the [ and ] keys.".
 - [x] Remove 'Select your commander' point since the commander is already selected. Add the "(Make sure your commander is selected)" paragraph. Put this above the tip paragraph.
 - [x] The bottom point should be "Left click on the ground to place the building" for consistency with Obj 8.
 - [x] Make sure that these changes avoid creating a scrollbar.
 - [x] Move the factory 16 elmos to the right as it would look better centered.

Objective 10:
 - [x] Add an objective for factory assist.
 - [x] Put a marker on the factory "Right click to assist".
 - [x] The only legal command should be a guard command given to the commander with the factory as the target. Currently any unit can recieve a guard command on any other unit.
 - [x] The large blue arrow is still pointing at the factory tab, remove it.
 - [x] The objective paragraph should sya "Right click on the factory to assist it. Assist is the most effective way to speed up unit production.".
 - [x] The commander is already selected so don't tell players to select their commander. Instead, add the "(Make sure your commander is selected)" paragraph at the bottom.
 - [x] The marker should say "Right click to assist the factory".
 - [x] It is hard to actually see the commander assisting the factory, due to model geometry. Move the construction location of the Solar Collector and/or the factory so that the commander is standing to the north or south instead of to the west.
 - [x] It is weird that the guard command in the order menu is not enabled. I know the technical reason for this, that the full guard command is much more powerful than assist, and new players don't really know that right click gives a guard command. I think we can leave it as is.
 
Objective 11:
 - [x] Again, remove the first sentence.
 - [x] "Build five Glaives with your factory." is better grammar. No need to call them "Glaive bots".
 - [x] The units tab is open by default, don't tell people to click it. At most tell them to select the units tab if it is not already selected.
 - [x] Say "Glaive button" for consistency with other objectives.

Objective 12:
 - [x] Text should say "Use attack move to destroy all enemies to the right. Press A and left click to issue an attack move order."
 - [x] Do no capitalize "Attack Move", no other commands are capitalized. Alternately you should capitalize everything.
 - [x] Marker should say "Attack move here".
 - [x] Move the marker 80 elmos to the left so the Glaives don't end up jittering on the LLT corpse.
 - [x] Glaive is still highlighted in the units tab of the factory.
 - [x] Orders more than 1200 elmos from the rocko spawn location should be illegal. There is no reason to give an attack move command to a location significantly to the right of the enemy commander. There is a reason to test out the commands in your own base area.
 - [x] Set the enemy commander to hold fire.

Objective 13:
 - [x] There should be no "Next" button, victory should simply occur as soon as this objective appears.
 - [x] I think "You now know..." is better grammar.

**Comment by GoogleFrog** [comment]
Missions are now started with startpostype = 2 and the modoption fixedstartpos = 1. This causes this big ready button to appear in the tutorial mission. I made changes in init_auto_ready (the gadget which overwrites start position drawing) to make nothing drawn. It seems that script missions override this gadget so the engine default is shown.

![screen00517](https://user-images.githubusercontent.com/1318249/29995769-5f409b3a-9034-11e7-8cde-c6e25aa80d8e.jpg)

**Comment by GoogleFrog** [comment]
@KingRaptor are you going to finish this off?

**Comment by KingRaptor** [comment]
- I've suppressed right-click-drag-on-feature area reclaim. I don't know of any way to block reclaim on Fight.
- For the integral issue I was assuming you'd make the necessary widget changes. If disabling the initial queue widget will prevent empty integral from appearing, I can use ZKME's widget disable hax.
