### ISSUE TITLE
Mutator dependancy existence is untestable

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#329]
Chobby tests that a game exists before trying to launch the game but it does not test for dependencies of mutators. How can these be seen?

**Comment by gajop** [comment]
See https://github.com/ZeroK-RTS/Chobby/blob/master/LuaMenu/widgets/chobby/utilities/package.lua

**Comment by gajop** [comment]
`local deps = VFS.GetArchiveDependencies(archiveName)` in particular; but i'd recommend using that function directly.

**Comment by Licho1** [comment]
What scenario exactly are we talking about? What mutators?

**Comment by GoogleFrog** [comment]
Missions. But I may have been mistaken.
