### ISSUE TITLE
If user leaves on disconnect, he can linger in battle

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#33]
If user is disconnect, only userdisconnect is sent, not extra user with battle nil. 
This can lead to user being stuck in battle (in hover icon)

**Comment by GoogleFrog** [comment]
This is why a leave battle command is nice.

**Comment by GoogleFrog** [comment]
Cannot reproduce. What is "hover icon"?

**Comment by Licho1** [comment]
Moving mouse over battle. I had it with firepluk who baecome AFK and then was disconnected. He was gone from lists but the battle tooltip still had him.

**Comment by GoogleFrog** [comment]
Probably fixed.
