### ISSUE TITLE
Chobby should not show "add ai" in games where AI is not allowed

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#34]
Adding bots is permitted only on coop and custom rooms, yet gui buttons are shown in team games as well.

**Comment by Skasi** [comment]
Buttons should probably remain, but be grayed out and have a tooltip explaining why AIs can not be added.

**Comment by GoogleFrog** [comment]
Screenshot.

**Comment by Licho1** [comment]
http://i.imgur.com/BIOoaJZ.png
this shows FFA game with add AI/ bots section .. this cannot be popuplated server blocks it.

**Comment by GoogleFrog** [comment]
I observed this when there was a lot of !type usage. A flobby user ended up on team 2 and this team tends to be called Bots.

**Comment by GoogleFrog** [comment]
Mostly works, needs checking.
