### ISSUE TITLE
Newer circuit config

### ISSUE THREAD

**Issue by ScorchedEarther** [ZeroK-RTS/Chobby#353]
Newer circuit Brutal config dated 24-09-17. Version currently in Circuit dev.

Place in

C:\Users\user\Documents\My Games\Zero-K\AI\skirmish\CircuitAIBrutal32\stable\config
C:\Users\user\Documents\My Games\Zero-K\AI\skirmish\CircuitAIBrutal64\stable\config

[circuit.zip](https://github.com/ZeroK-RTS/Chobby/files/1417771/circuit.zip)

**Comment by GoogleFrog** [comment]
Typo on line 2090.

**Comment by GoogleFrog** [comment]
Here is a good page on how to make a pull request just using the web UI. https://github.com/WGBH/pbucore/wiki/Contributing-to-the-project-through-Github-web-interface

It would be good to go through the PR system as then comments can be made and tracked. As it is I had to copy your zipped file into a diff checker manually.

**Comment by ScorchedEarther** [comment]
With typo removed

[circuit 2.zip](https://github.com/ZeroK-RTS/Chobby/files/1336465/circuit.2.zip)

Apologies for the need perform manual process. I probably won't be making another one of these for a long time now.

**Comment by ScorchedEarther** [comment]
Typo has been corrected btw.

**Comment by GoogleFrog** [comment]
I know, I have been busy for the last week or so. Usually I get a little time while otherwise busy to go through PRs and either make comments or pull them. This isn't a PR though so I will need a dedicated block of time on my home computer to deal with it.

**Comment by ScorchedEarther** [comment]
Updated file with sexy new version. Various minor improvements.

**Comment by lagerspetz** [comment]
I made a PR out of this to make things easier.

**Comment by GoogleFrog** [comment]
The PR was merged.
