### ISSUE TITLE
Implement session token to login to website when opening url

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#36]
1) LoginResponses sends SessionToken, store this (string)
2) append SessionToken to URL being opened.

If URL contains zero-k.info,  and does not contain "asmallcake" append ?asmallcake=<SessionToken>
If URL already contains "?" append &asmallcake=<SessionToken>

It is strictly needed just for the first visit of the session, then website will remember association and store another session in browser's cookies.

See this for server side implementation:
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/669bbfec7814bb5a7da4ee3c33991e2800e9c711

**Comment by GoogleFrog** [comment]
What if the URL contains "asmallcake" and "?". What about neither?

**Comment by Licho1** [comment]
neither -> added ?asmallcake=<sessiontoken>

if it contains a smallcacke (with ? or & or anything else) do nothing, or better yet, replace it with proper session token (player most likely clicked link meant originally for osmeone elsE)

**Comment by GoogleFrog** [comment]
What if there is no "zero-k.info"?

**Comment by Licho1** [comment]
if there is no such address then probably no session token manipulation is needed (URL is not on ZK site and does not need automated logon)

**Comment by Licho1** [comment]
You also need to support https and also in theory someone could make stuff like
http://zero-k.infowars.com/ 
so check it either ends with zero-k.info or next char is / and thats it.

**Comment by GoogleFrog** [comment]
Close this if you like @Licho1

**Comment by Licho1** [comment]
Were there any more commits?

**Comment by GoogleFrog** [comment]
Yes.

**Comment by Licho1** [comment]
looks good
