### ISSUE TITLE
compatibility mode turned off on latest version for AMD user

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Chobby#367]
See https://github.com/ZeroK-RTS/Zero-K/issues/2574

**Comment by Sortale** [comment]
is compatibility mode supposed to be turned on?

with it some other graphics problem is present 

e.g. nano become really bad lazer graphic, not the nice lazer graphic one

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Chobby/commit/c7755cf156e2f7c50f8aa44daad307dd5cd913fa.
