### ISSUE TITLE
Campaign start is not obvious

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#372]
It is not sufficiently clear how to start the campaign. Here are some ideas for fixing this.
- Perhaps add a "Start here" arrow.
- Zoom the galaxy view to a bounding box around the currently visible planets. This would make the initial planets quite large and slowly revealing the extent of the galaxy could have a nice effect.

**Comment by gajop** [comment]
If you can pull 2) off that would have a very interesting effect. That said, trivial implementation (via image zoom) would need a relatively base image in order to reduce pixelization.
