### ISSUE TITLE
My peewee is huge after playing campaign

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#376]
It seems the scale that is applied to the galaxy is afterwards also applied to the default background image.

![huge peewee](https://i.imgur.com/u6FuufR.png)

**Comment by GoogleFrog** [comment]
Already done https://github.com/ZeroK-RTS/Chobby/commit/e2e65316d7dbacd7bcc9938744dbb1efaf46085f

**Comment by DeinFreund** [comment]
Sorry I just had to make this ticket.
