### ISSUE TITLE
Signalize parties in player listings

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#378]
It would be nice to see who is already in a party and even better if you could see who is partied with whom, especially in battle rooms. Is there anything speaking against adding a partyID field to the `User` message?

**Comment by Licho1** [comment]
Issues are:
- we would need to sync user entity for each (unrealted party change)
- you could discover other person's party which might not be what people like

I'm not sure if its worth the extra traffic if there is a sensibile GUI implementation though we can add it..

**Comment by GoogleFrog** [comment]
I don't think this change is worthwhile. Perhaps it is worth while to see the partyID of your friends so you can request to join their party.

**Comment by DeinFreund** [comment]
The main reasons for this were:
 * See whether somebody is available for parties or already inside one
 * Explain weird balance in public rooms

I'd like to have some feedback along the lines of "unable to invite X to party because he's already partied".

**Comment by Licho1** [comment]
Imo if you have a matching GUI request it should be done, otherwise it is doing a backend without having frontend plan..
