### ISSUE TITLE
Skirmish UI Next button is off-screen on 1366x768

### ISSUE THREAD

**Issue by db81** [ZeroK-RTS/Chobby#385]
![screenshot from 2017-11-06 13-27-35](https://user-images.githubusercontent.com/2241548/32424334-6ceec3d8-c2f7-11e7-876c-b5a787a2fe9d.png)

I suggest doing away with the button and having clicking on the difficulty or skirmish mode forward you to the next page, that's the behavior I expected at least.

**Comment by gajop** [comment]
I agree - next button is unnecessary.

**Comment by GoogleFrog** [comment]
Without a next button you are taken through too quickly. Selecting an option becomes a risk because you are suddenly on a new page. This is a real thing I have observed in people.

**Comment by db81** [comment]
Regardless of whether we keep Next, there should be a back button.
