### ISSUE TITLE
Zero-K Steam looks for non-existent Zero-K.sh

### ISSUE THREAD

**Issue by lagerspetz** [ZeroK-RTS/Chobby#389]
Zero-K does not start on Steam since today. It is looking for a script called Zero-K.sh. The script included in Zero-K is Chobby.sh, and it should be renamed to Zero-K.sh to fix this problem.

**Comment by Licho1** [comment]
Sorry for that, it is part of the process of renaming chobby.exe to zero-k.exe
It is not yet live but steam has been updated alread.y Please start manually until we fix it (probably tommorow).
