### ISSUE TITLE
After download, chobby still shows missing resource

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#393]
1) have a friend host titan duel game
2) delete titan duels
3) start chobby, let it dl (possibly mess with prioritites, move to top etc)
4) chobby will still show titan dual as missing, but upon joining no dl happens

**Comment by GoogleFrog** [comment]
What exactly is titan duel? Is it a featured map?

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Chobby/commit/c4f0398afa6fbcb6523f223553bf5088e8842e2b.
