### ISSUE TITLE
"Downloads" tab don't display actual progress

### ISSUE THREAD

**Issue by Kefirman** [ZeroK-RTS/Chobby#398]
![image](https://user-images.githubusercontent.com/6818434/32703181-14f53200-c803-11e7-99d8-bdb2f97783b7.png)

Download tab shows, that map is being download, but it was downloaded long ago, and even played on it.
It always show "connecting" state, even if download in progress, which isn't shown. People think that automatic download don't work and starts to panic.

**Comment by ashdnazg** [comment]
lol @ room name
