### ISSUE TITLE
Lobby Menu button overlaps with ingame settings menu

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#40]
Also there are some weird blue stripes:
![1](https://i.imgur.com/Tt9aJmO.png)

**Comment by GoogleFrog** [comment]
The stripes are part of the UI, they deliminate the middle area. The lobby menu button is going to go there so its a ZK issue.

**Comment by DeinFreund** [comment]
I think the transparency, especially of the blue stripes makes it look weird. I would recommend rendering all "windows" solid (that is the blue stripe, the Battle Screen, and the chat screen when opened) similarly to how steam's overlay looks

**Comment by Licho1** [comment]
Just make it pure "white/gray" transparency. Colored tints are odd.

**Comment by GoogleFrog** [comment]
Removed button.

**Comment by Licho1** [comment]
Removed? How is it replaced now? with f11 ingame button?

**Comment by GoogleFrog** [comment]
Yes. Old versions of ZK will still display the button on top of the UI because ZK must send a message to chobby to tell chobby to not display the button.
