### ISSUE TITLE
Map download progress is not shown

### ISSUE THREAD

**Issue by Trojaner25** [ZeroK-RTS/Chobby#410]
Map is downloading (as clearly visible on the infolog), but progress is not shown.
Instead it shows "Connecting..." as seen here:
![bug](https://vgy.me/HmQely.png)
[infolog_full.txt](https://github.com/ZeroK-RTS/Chobby/files/1491466/infolog_full.txt)

In this example its `MoonQ10x` but any map is affected.
It will show "Complete" once its finished which you an also see on the image.

**Comment by GoogleFrog** [comment]
European numbers Zero-K.exe Information: 0 : Chobbyla >> DownloadFileProgress {"FileType":"MAP","Name":"Adansonia v4.1","Progress":"21,11","SecondsRemaining":20,"TotalLength":37363087,"CurrentSpeed":1457896}.

**Comment by Trojaner25** [comment]
Has been fixed
