### ISSUE TITLE
Add option to ignore party invites.

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#432]
Imagine a tournament with 100 spectators and just a few of them constantly spamming the players with party invites. They will be unable to do anything because of all the pop-ups.

The same goes for streamers..

**Comment by DeinFreund** [comment]
I think this belongs on infra.

**Comment by Licho1** [comment]
invites can also happen via steam

**Comment by DeinFreund** [comment]
Steam has its own filtering.
