### ISSUE TITLE
Chobby website integration failing

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#437]
1) start chobby
2) go to website
3) find a map
4) click "play on this map"

-> nothing changes in chobby.
It used to work. Its quite important that we dont have broken buttons

**Comment by DeinFreund** [comment]
`[02:52] <--SiteToLobbyCommand {"Command":"chat/battle@select_map:TitanDuel 2.2"}`
command arrives at chobby

**Comment by Licho1** [comment]
it did nothing when i was not in battle room

**Comment by GoogleFrog** [comment]
Why would it do anything when not in a battleroom?

**Comment by Licho1** [comment]
There is a button on web regardless of lobby state. . "play on this map" .. in ZKL it would just open a room with this map or change map of current room. It makes sense and should be easy to do but this is actually a server solveable issue so feel free to move it to infra,

**Comment by GoogleFrog** [comment]
Ok I will open a battleroom. Does host battle take map as an argument?
