### ISSUE TITLE
Changing to the "Replays" tab freezes the lobby temporarily

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Chobby#44]
Changing to the "Replays" tab freezes the lobby client for about 7-20 seconds on my machine. One could even accidentally click on the tab button. Please try to get rid of the unresponsiveness and add a progress bar if changing to the tab takes a long time. Progress bars for individual replays would be even better.

**Comment by Sgathec** [comment]
Sorry, GoogleFrog, it still freezes Chobby at least on my PC. The last time I changed to the tab I had to wait about 28-35 seconds. The duration hasn't necessarily gone up though as I probably just failed to recall the amount of time correctly. This time I think the assessment is more accurate to an extent.

**Comment by GoogleFrog** [comment]
Describe what happens or take a video.

**Comment by Anarchid** [comment]
Wasn't this resolved?

**Comment by Sgathec** [comment]
No, unfortunately not. Yesterday, right after opening Chobby, I tried to view replays and it froze. In the end, there were 4-6 replays on the list.
