### ISSUE TITLE
Open the commander tab after 1st mission

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Chobby#441]
Saktoth's tips:

>You need to bring it up after a battle when you unlock your first stuff.
>You need to tell the player where they are being rewarded by opening that screen for them.
>Just literally bring the screen up after your first unlock.

**Comment by GoogleFrog** [comment]
Maybe that is better than highlight, and easier.

**Comment by GoogleFrog** [comment]
Done https://github.com/ZeroK-RTS/Chobby/commit/3815808aae7476ea0da1d33285fddee4451fa558.
