### ISSUE TITLE
Make 'Auto' ATI/Intel Compat option and detect GPU every time

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#442]
usepbo =0  does not seem to be applied, breaking map rendering.

**Comment by GoogleFrog** [comment]
Check infolog 	

self.atiIntelCompat = self:GetIsNotRunningNvidia()
Spring.Echo("Initialize ATI/intel/other non-nvidia compatibility state:", self.atiIntelCompat)

Check the state of "ATI/Intel Compatibility" in the graphics settings menu.

**Comment by Licho1** [comment]
ATI compatibility is default off for me. Why ?

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Chobby/blob/master/LuaMenu/widgets/chobby/components/configuration.lua#L647

What is boils down to is that Spring has a global lua table called Platform. If Platform.gpuVendor ~= "Nvidia" then I set Intel/ATI compatibility. The other stuff in that function legacy for the time before Spring had such a table.

**Comment by Licho1** [comment]
This is probably caused by steam account syncing.
Make the config option for AMD: auto/on/off with default being auto.

**Comment by GoogleFrog** [comment]
Actually @Licho1, can you test this with sync.

**Comment by Licho1** [comment]
With sync? Well still happens.

**Comment by GoogleFrog** [comment]
Try latest.
