### ISSUE TITLE
Update featured map list

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Chobby#444]
Needs to be done manually for now. See https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1950

**Comment by Licho1** [comment]
I dont understand.
What is the purpose of having a list of featured maps in chobby?

**Comment by GoogleFrog** [comment]
Chobby has a local map list, it needs a featured map list to filter out old versions. Ideally the server would generate a json file and deploy it from the wrapper. This would contain all information about maps featured and above. Some information.
 - Name
 - Rating
 - Terrain type
 - Width, height
 - 1v1, chickens, FFA etc..
 - Featured level.

**Comment by Licho1** [comment]
Now i undertand

**Comment by Licho1** [comment]
Done, community now contains MapList with these entries:
``` 
    public class MapItem
    {
        public int ResourceID { get; set; }
        public string Name { get; set; }
        public MapSupportLevel SupportLevel { get; set; }
        public int? Width { get; set; }
        public int? Height { get; set; }
        public bool? IsAssymetrical { get; set; }
        public int? Hills { get; set; }
        public int? WaterLevel { get; set; }
        public bool? Is1v1 { get; set; }
        public bool? IsTeams { get; set; }
        public bool? IsFFA { get; set; }
        public bool? IsChickens { get; set; }
        public int? FFAMaxTeams { get; set; }
        public int? RatingCount { get; set; }
        public int? RatingSum { get; set; }
        public bool? IsSpecial { get; set; }
    }

```
