### ISSUE TITLE
First time users are not immediately presented with a Register screen, allegedly

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#446]
I dimly recall @Licho1 making this claim recently in some channel. I just deleted luamenu and was greeted with a "pick your name for steam linking" screen on startup. I then deleted luamenu and shutdown steam and was greeted with a "register your login and password" screen on startup.

**Comment by Licho1** [comment]
tested without steam, and with steam fresh account, worked correctly.
