### ISSUE TITLE
Problems with Ladder display

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#450]
![blub](https://i.imgur.com/vG1uKaq.png)

Countries and icons are contained in LadderList but not shown:
```
LadderList {"LadderItems":[{"Name":"Sigero","Clan":"MC","Icon":"7_6","Level":110,"Country":"RO","IsAdmin":false,"AccountID":314871},{"Name":"GoogleFrog","Clan":"RSN","Icon":"7_6","Level":128,"Country":"AU","IsAdmin":true,"AccountID":15114},{"Name":"DeinFreund","Icon":"7_5","Level":154,"Country":"CH","IsAdmin":true,"AccountID":232028},{"Name":"Anir","Clan":"MC","Icon":"6_5","Level":95,"Country":"LU","IsAdmin":false,"AccountID":220940},{"Name":"raaar","Icon":"7_5","Level":110,"Country":"PT","IsAdmin":false,"AccountID":142479},{"Name":"gajop","Icon":"5_5","Level":69,"Country":"JP","IsAdmin":false,"AccountID":89992},{"Name":"hokomoko","Clan":"MC","Icon":"6_4","Level":100,"Country":"IL","IsAdmin":true,"AccountID":169779},{"Name":"Firepluk","Icon":"7_4","Level":255,"Country":"RU","IsAdmin":false,"AccountID":185685},{"Name":"NorthChileanG","Clan":"MC","Icon":"7_4","Level":190,"Country":"EE","IsAdmin":false,"AccountID":257950},{"Name":"Kingstad","Clan":"Loaf","Icon":"6_4","Level":76,"Country":"NO","IsAdmin":false,"AccountID":188160}]}
```

**Comment by GoogleFrog** [comment]
Country is not in the static ladder list "LadderItems":[{"Name":"Sigero","Clan":"MC","Icon":"7_6","AccountID":314871},{"Name":"GoogleFrog","Clan":"RSN","Icon":"7_5","AccountID":15114},{"Name":"Fealthas","Clan":"ELOn","Icon":"6_5","AccountID":218372},{"Name":"DeinFreund","Clan":null,"Icon":"7_5","AccountID":232028},{"Name":"Anarchid","Clan":"TheGBC","Icon":"7_5","AccountID":60947},{"Name":"Llamadeus","Clan":null,"Icon":"5_5","AccountID":59430},{"Name":"Anir","Clan":"MC","Icon":"6_4","AccountID":220940},{"Name":"raaar","Clan":null,"Icon":"7_4","AccountID":142479},{"Name":"Firepluk","Clan":null,"Icon":"7_4","AccountID":185685},{"Name":"Flipstip","Clan":null,"Icon":"7_4","AccountID":169648}]

**Comment by Licho1** [comment]
It is in BOTH. It just waits stable deployment... Cannot do it until go
ahead from DeinFreund.

**Comment by DeinFreund** [comment]
Yes sorry, I just noticed it wasn't deployed yet. Will let you know when deployed.

**Comment by DeinFreund** [comment]
This has been deployed now.
