### ISSUE TITLE
Settings menue gone

### ISSUE THREAD

**Issue by Ubimo** [ZeroK-RTS/Chobby#452]
Hello
I just clean-installed the web-version in windows. When in chobby clicking on settings -> interface -> camera pan speed the menue disappears and won't reappear until chobby restart.

**Comment by Ubimo** [comment]
Video: https://youtu.be/t7YR0oOiTDE

**Comment by darloth** [comment]
I have the exact same issue. 

I'm running a new install on a windows 10 machine.

**Comment by KingRaptor** [comment]
Fixed in next stable, thanks for reporting!
