### ISSUE TITLE
Unusual error on setting modoptions.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#46]
The server sends me back 'Dictionary`2' instead of what is expected so chobby never displays the modoption change.

[f=-000001] Server, >SetModOptions {"Options":{"waterlevel":"120"}}
[f=-000001] [liblobby] Error: No such function: Dictionary`2, for command: Dictionary`2 {"waterlevel":"120"}
[f=-000001] Server, <Dictionary`2 {"waterlevel":"120"}
[f=-000001] Server, >SetModOptions {"Options":{"waterlevel":"120"}}
[f=-000001] [liblobby] Error: No such function: Dictionary`2, for command: Dictionary`2 {"waterlevel":"120"}
[f=-000001] Server, <Dictionary`2 {"waterlevel":"120"}

**Comment by GoogleFrog** [comment]
The modoption is set correctly ingame.

**Comment by Licho1** [comment]
fixed in server
