### ISSUE TITLE
Battle list ordering

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#460]
![full](https://i.imgur.com/lFEp1nD.png) 

Luckily the game seems to be becoming more popular. This brings up room ordering again (although I couldn't find the previous issues). I'd suggest ordering rooms by

1. Non-passworded rooms first
2. Non-full rooms first
3. Amount of players descending

**Comment by Fealthas** [comment]
Bring back filters!

**Comment by GoogleFrog** [comment]
I think filtering is a sufficient fix.

**Comment by Licho1** [comment]
Imo sorting is still needed.

**Comment by GoogleFrog** [comment]
I also fixed sorting.
