### ISSUE TITLE
Community images seem wonky at times

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#461]
I have started chobby after long time, this is how community looks:

https://i.imgur.com/Z2MZmP0.png

second start:

https://i.imgur.com/kvLN4Aa.png

 * news images were not displayed first start
 * country images never displayed

**Comment by gajop** [comment]
were any of those players logged in? I think that's required to display country images

**Comment by GoogleFrog** [comment]
Fixed.
