### ISSUE TITLE
[Linux] Single player missions not working.

### ISSUE THREAD

**Issue by ghost** [ZeroK-RTS/Chobby#463]
When I open the website and I go to Play->Missions and click on "Play Now" button on a mission, nothing happends . I don't know why does this happen . The site detects that Chobby is open (Does not display "To use this feature, you need to be running the game and be logged in there")

**Comment by DeinFreund** [comment]
Should we remove them from the website? For all I know Chobby isn't supposed to support them currently.

**Comment by IKRadulov** [comment]
If you could support them it would be awesome . Can I download a version witch supports them ?

**Comment by IKRadulov** [comment]
I just noticed the same is happening with the maps .

**Comment by DeinFreund** [comment]
#437 for maps. They should work fine if you're in a lobby.

**Comment by GoogleFrog** [comment]
The "Play Now" button is not supported and does nothing. It could be made to do something with quite a bit of a low priority work so it is better off hidden for now.

**Comment by Licho1** [comment]
It is easy to make it switch to a map in MP game room at least. Similar stuff could be possible with mission but mission MP hosting is completely unimplemented atm in chobby and probably not worth the effort.

**Comment by GoogleFrog** [comment]
Switching to maps in MP room is implemented already.

**Comment by IKRadulov** [comment]
What happened with missions. I remeber they were supported once .

**Comment by sprunk** [comment]
ZeroK-RTS/Zero-K-Infrastructure@0a0156d98025ae009efe334354bf91b0f1bab99c
