### ISSUE TITLE
!map comand does not pick correct map

### ISSUE THREAD

**Issue by Fealthas** [ZeroK-RTS/Chobby#464]
Current behavior:
`!map red comet` picks "red comet" and leaves a message about it being the unsupported version and asks if we mean "red comet v1.3".

Expected behavior:
`!map red comet` picks the correct version of the map. 

Perhaps !map should not pick unsupported map unless it gets a flag -u or something.

**Comment by sprunk** [comment]
This is done on purpose so that people can easily pick unsupported maps, see https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/1972

(Personally I agree that it would be good if this picked the proper map right away but the consensus is otherwise)

**Comment by Fealthas** [comment]
It is very noob friendly to have to know which version of a map to pick. Good job devlobs.

**Comment by sprunk** [comment]
`!map` doesn't have to be noob friendly because noobs won't even know about the command. They are supposed to use the "Select Map" button which brings up a nice browsable list which only contains featured maps.

**Comment by Aquanim** [comment]
IMO it needs to be possible to select an unsupported map using its verbatim name, but that functionality does not necessarily need to be exposed through the !map command.

**Comment by sprunk** [comment]
I checked and `!map red com` incorrectly picks `COMet catcher REDux v3.1`. It should prioritise `Red Comet v1.3` because the words appear in the same order as specified. Otherwise everything looks as expected.

**Comment by sprunk** [comment]
Done https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/cbe8edd91ac53f4212969adf348d6f9639c844b1
