### ISSUE TITLE
First launch polish

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#471]
- Do not show community tab on launch until the player has started a battle. They don't need distracting with it.
- Preload all images.

**Comment by Licho1** [comment]
I think community is a thing to show before first game. It is important to show things are active here.

**Comment by Aquanim** [comment]
I believe the concern is that it is complicated and may confuse people who are new to the interface.

**Comment by Licho1** [comment]
Confuse how? News popups seem to be fairly common. Do you think they will be lost and unable to find singleplayer?

**Comment by GoogleFrog** [comment]
What are the potential benefits of showing the community page on the first launch?
- We give some impression of activity, but this is low.
- Maybe people join discord immediately.

Downsides:
- It is harder to find the correct button on the menu (MP or SP).
- Clicking on any of the buttons takes the player away from the game, distracting them. They may not come back.
