### ISSUE TITLE
Initialize crash

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Chobby#480]
```
[f=-000001] [LuaMenu] Error: Failed to load config: error = 3, LuaMenu/Config/IGL_data.lua, [string "LuaMenu/Config/IGL_data.lua"]:1: unexpected symbol
[f=-000001] [LuaMenu] Warning: Failed to load: LuaMenu/Config/IGL_order.lua  (error = 3, LuaMenu/Config/IGL_order.lua, [string "LuaMenu/Config/IGL_order.lua"]:1: unexpected symbol)
[f=-000001] Error: [LuaMenu::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=Initialize trace=[Internal Lua error: Call failure] error = 2, LuaHandler/handler.lua, error = 3, LuaMenu/Config/IGL_data.lua, [string "LuaMenu/Config/IGL_data.lua"]:1: unexpected symbol
stack traceback:
	[C]: in function 'Include'
	[string "LuaHandler/Utilities/utils.lua"]:123: in function 'include'
	[string "LuaMenu/main.lua"]:54: in main chunk
```

 * https://github.com/ZeroK-RTS/CrashReports/issues/3358
 * https://github.com/ZeroK-RTS/CrashReports/issues/3360
 * https://github.com/ZeroK-RTS/CrashReports/issues/3361

**Comment by GoogleFrog** [comment]
Isn't the engine (or base content) supposed to check these files for validity and discard them if they are broken?

**Comment by sprunk** [comment]
I don't think it has the means to check for validity (what would it compare against?)

**Comment by GoogleFrog** [comment]
Check whether they fail to load because the file is not a valid lua table.

**Comment by sprunk** [comment]
https://github.com/spring/spring/pull/364

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Chobby/commit/c30839a7957f7d884d8223b188d78d77185c49e7
