### ISSUE TITLE
4K Scaling Issues 

### ISSUE THREAD

**Issue by nubtron** [ZeroK-RTS/Chobby#489]
Tried the lobby with a 4K monitor. This is with 150% scaling in Windows, which is the default value for a 4K monitor.

Here what the maximized lobby looks like:
![spring_2018-02-17_13-25-30](https://user-images.githubusercontent.com/49084/36340909-6b99989c-13e6-11e8-9391-d5543d135ccd.jpg)
Note the missing chat tabs.

When I resize the window below a certain threshold, the tab content suddenly appears in and is huge:
<img width="955" alt="spring_2018-02-17_13-25-21" src="https://user-images.githubusercontent.com/49084/36340922-90761456-13e6-11e8-9790-626810cbcfcc.png">

The campaign window looks like this, maximized:
![spring_2018-02-17_13-21-03](https://user-images.githubusercontent.com/49084/36340930-ad5159f0-13e6-11e8-907d-5479c1f9b091.jpg)

And this is what I see when I click on a planet:
![spring_2018-02-17_13-21-31](https://user-images.githubusercontent.com/49084/36340934-c74df87c-13e6-11e8-8b1f-f8bbb27f199d.jpg)

**Comment by GoogleFrog** [comment]
Infolog and data. I see no way for the default scaling to be 150%. Full screenshots are better. How did you run this?

**Comment by GoogleFrog** [comment]
Fixed,
