### ISSUE TITLE
Native AI crash

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Chobby#49]
The issue with native AIs and chobby described here: http://zero-k.info/Forum/Thread/23253
Fixed: https://github.com/spring/spring/commit/ddbb5ca71effc9128ea6cac154314d416d8c1e87
Current engine version that chobby use (103.0.1-296-g723eb8f) don't have the fix.

**Comment by GoogleFrog** [comment]
Fixed.
