### ISSUE TITLE
Move campaign difficulty combobox to main screen.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#503]

**Comment by Licho1** [comment]
No? Do not do this its better on campaign screen

**Comment by GoogleFrog** [comment]
I think you are confused about the state of the code. Describe exactly what you are seeing and the problem that you have.

**Comment by Licho1** [comment]
ok it looks a bit out of place but its fine

**Comment by GoogleFrog** [comment]
Better than players not knowing that difficulty exists or how to change it. Also I like to be able to see what difficulty a mission will be just before playing it. Previously I found myself checking the submenu to be sure.

**Comment by Licho1** [comment]
Yes it is better this way
