### ISSUE TITLE
Clicking on campaign after joining a Multiplayer lobby doesn't close the lobby.

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#513]
It's not intuitive why the campaign isn't shown. When clicking Singleplayer -> Campaign it might make sense to leave any joined multiplayer rooms or at least ask the player what he wants to do.
![campaign](https://i.imgur.com/yRBlMCy.png)

**Comment by Licho1** [comment]
I dont think it should quit MP.
As long as it shows campaign screen it is ok.
One of the purpose of SP is to play SP while you wait 12h for your MP game to start.

**Comment by DeinFreund** [comment]
A friend was trying zk for the first time and while he was waiting for MP I told him to play campaign. HE couldn't play campaign because the MP window was blocking the campaign view.

**Comment by GoogleFrog** [comment]
I don't know what you are talking about as 'close' is a bit ambiguous. Do you want to leave the lobby or hide the lobby? Leaving is probably justified. Hiding it would be confusing.

**Comment by DeinFreund** [comment]
I'm also for leaving the lobby because a sudden multiplayer game starting would be confusing. Some players might be annoyed by this though.

**Comment by Licho1** [comment]
I would hide it but not sure.. confusion might be real if thats not what person wanted

**Comment by Licho1** [comment]
on the other hand one can join lobby after sp starts, right?

**Comment by GoogleFrog** [comment]
Yes.

**Comment by Licho1** [comment]
Yeah in that case its no brainer to quit room...
