### ISSUE TITLE
Edit box focus cycle on register window is wrong

### ISSUE THREAD

**Issue by vladmihaisima** [ZeroK-RTS/Chobby#519]
Open Chobby, click Multiplayer, click Register tab, click Username edit box, press "tab", focus moves to "Password" edit box, press "tab", focus moves to "Username" edit box.

Expected behaviour: for last action (second press of "tab") focus moves to "Confirm" edit box.

A new user entering user and passwords (twice), by typing and pressing tab, this without looking at the screen and got confused why he could not register.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Chobby/commit/d95ebf14b8e4023dbd665e515f5124efb6bae636.
