### ISSUE TITLE
Links opened from chobby dont log you to website

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#525]
This causes crashes on links like 
http://zero-k.info/Planetwars/Planet/4344

**Comment by GoogleFrog** [comment]
Did you test as admin? I don't send admin steam tokens because people suck too much at not revealing their secret URLs to the world. https://github.com/ZeroK-RTS/Chobby/blob/master/LuaMenu/widgets/api_internet_browser.lua#L43

**Comment by Licho1** [comment]
Ok didnt realize it was admin filter but you eanbled it anyway
