### ISSUE TITLE
Excess chat tabs are simply hidden

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Chobby#54]
After opening a certain number of chat tabs, the tab buttons that don't fit the designated area aren't displayed at all anywhere. I have only seen this happen in the two-panel mode.

**Comment by GoogleFrog** [comment]
Yep. It's not something I'm all that interested in so is a good candidate for a PR.

**Comment by GoogleFrog** [comment]
Fixed in the lazy way with a scrollbar.
