### ISSUE TITLE
After server crash chobby remained "frozen"

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#545]
After server crash, which resulted in instant disconnect of all players, chobby stayed the same, showing no indication of any problem.
Green light was green but nothing would respond.

**Comment by DeinFreund** [comment]
Duplicated of #239 i think.

**Comment by Licho1** [comment]
If you cannot detect socket disconnect directly, just watch when you get last server message.
If no message for 2 minutes - reset stuff and try reconnect.
MatchMaker spams every 30s anyway.

**Comment by GoogleFrog** [comment]
Fixed.
