### ISSUE TITLE
Nothing to indicate who is being ignored

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Chobby#57]
The user isn't displayed anything in order to remind that a person is being ignored. Because one could possibly like to unignore the target person after an amount of time, perhaps the background of the ignored person's name should be tinted red. Alternatively I think the name could be stricken through with a transparent red line. Currently, it is also tricky to view or unignore applicable people who are not logged in.

**Comment by GoogleFrog** [comment]
Ignored people are now grey.
