### ISSUE TITLE
Other people's campaigns can override yours

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Chobby#572]
After completing a savegame from someone else's campaign, their campaign progression data overrides your own. (Occurred to me while testing https://github.com/ZeroK-RTS/Zero-K/issues/2994)
I've heard of it also happening during co-op. 

It should create a new campaign save profile instead of replacing the current one.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Chobby/commit/f12b0de4983d49bca002ab491cc1175756664f3d
