### ISSUE TITLE
Remove maps from Chobby defaultSettings

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Chobby#576]
There have been complaints over the game update size on Steam (e.g. [here](https://steamcommunity.com/app/334920/discussions/1/1696046342866774580/)), which is due to having to re-download the .sdzs.

For Chobby updates, this could easily be remedied by removing the maps from the [`gameConfig/defaultSettings`](https://github.com/ZeroK-RTS/Chobby/tree/master/LuaMenu/configs/gameConfig/zk/defaultSettings) folder. chobby.sdd (without the .git folder) is 388 MB, of which the maps take up 238 MB.

There is no need to include the maps in the Chobby archive, as both Steam and the itch portable should have no issues guaranteeing their deployment, and in the worst case Chobby can just auto-download them from springfiles.

**Comment by KingRaptor** [comment]
Related to Spring-Chobby/Chobby/issues/439

**Comment by GoogleFrog** [comment]
Can this be done without breaking any of the packaging systems?

**Comment by KingRaptor** [comment]
The old installer-based download (Zero-K.setup.exe) and Debian installation file will only download the maps on first run, if we still care about supporting those. I don't know of any other distribution method that would be affected.

**Comment by GoogleFrog** [comment]
Terrifying.
