### ISSUE TITLE
[Steam beta branch] Campaign widget crash

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Chobby#587]
After completing mission 1:
```
[f=0011512] [LuaMenu] Error: In RecvLuaMsg(): <function>
[f=0011512] [LuaMenu] Error: Removed widget: <Campaign Handler>
```
The campaign menu buttons disappear from Chobby (in 2-panel mode, this means everything except Exit).

**Comment by KingRaptor** [comment]
Infolog: https://github.com/ZeroK-RTS/CrashReports/issues/7030

**Comment by GoogleFrog** [comment]
Is this a thing it does reliably?

**Comment by GoogleFrog** [comment]
Then locally overwrite the widget (if possible) and add debug output.

**Comment by KingRaptor** [comment]
Can no longer reproduce.
