### ISSUE TITLE
Chobby mustn't rejoin queues after game start

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#589]
When a MM game starts, it could be that chobby isn't told to leave the queues before the game starts. If the message to leave queues arrives during game load, could it be that Chobby still rejoins the queues after load is complete?

**Comment by GoogleFrog** [comment]
Why don't you test this?

**Comment by GoogleFrog** [comment]
This ticket isn't telling me what is going on, or exactly what should happen. Make ticket that contains a series of observations and suggestions for better behaviour. This ticket seems to be hindering communication.

**Comment by DeinFreund** [comment]
I think #619 is another one of these.
