### ISSUE TITLE
Chobby disrespects its boundries (Can join 'locked' channels)

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Chobby#59]
Affects only #Hegemony and #Rising

**Comment by GoogleFrog** [comment]
Sounds like a server issue. If chobby can do it then any lobby could be written to do it.

**Comment by ArchShaman** [comment]
Close and move to Infra?

**Comment by Licho1** [comment]
This belongs to infra however are these real active factions?

**Comment by ArchShaman** [comment]
Yes, I was able to be voted into Rising as Mastermind.
