### ISSUE TITLE
Match making join type order keep changing

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Chobby#598]
https://steamcommunity.com/sharedfiles/filedetails/?id=1390390481

The view above is not consistent with the usual layout.

**Comment by GoogleFrog** [comment]
Check that this still occurs.

**Comment by Sortale** [comment]
still occur as of 2 months ago, the problem is that it randomly happen and I do not know what triggers it and so in a sense un-reproducible. 

Unless I restart zk a hundred times and check the MM screen every time maybe?

**Comment by Sortale** [comment]
still current, I just restarted zk 5 times and the 5th times It get this order, which I don't think is the correct order

https://i.imgur.com/UnyK96F.jpg

**Comment by Sortale** [comment]
I seem to be able to replicate it by 
starting zk
the as quickly as possible [less than about 7 secondd], click through to the Matchmaking page before it can load
when it finally load, this:
https://i.imgur.com/UnyK96F.jpg
the layout would be used and stay like that until close


if you wait for more than 20 sec after start before looking at MM page the normal layout would be used
