### ISSUE TITLE
Lobby music volume not remembered

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Chobby#61]
See https://github.com/ZeroK-RTS/Zero-K/issues/1641

> New Lobby, music volume is set at maximum when lobby starts, even if settings say it is lower.
> Selecting volume sliders returns it to correct level, even if you don't adjust it.
> (Its not a big issue).
> 
> BTW thanks for fixing the fullscreen bug so quickly Googlefrog, nice job.

**Comment by GoogleFrog** [comment]
Seems fixed.
