### ISSUE TITLE
Newspost event time displays incorrectly when timezone change rolls over month

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Chobby#630]
The 3v3 tournament post has event time 8/31/2018 8:00:00 PM.

In Chobby (which converts to local time) this displays as the 32nd of August 6am local time.

**Comment by sprunk** [comment]
https://github.com/Spring-Chobby/Chobby/blob/cee74fa344a973f5106bfe8cdd32615b8ea6b994/LuaMenu/Addons/timeFunctions.lua#L65-L72

Looks like the month fixing loop is never entered. Also it looks like 24:60 would not be converted to 01:00 the next day either. Sounds easy to fix but it's important enough that I don't want to do it blind.

**Comment by sprunk** [comment]
5afda92b0363bd4849a83281228c8fd7d777e6b2
