### ISSUE TITLE
Implement new AreYouReady information

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#631]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/2395 brings additional information to AreYouReady about what game the players are going to play. There are new attributes:
 * `MinimumWinChance` (double) the minimum win chance currently guaranteed in Teams when player is using quickplay, if there is no guaranteed minimum win chance, `-1`.
 * `QuickPlay` (bool) set if the player was joined into the MatchMaker automatically because he just finished a big teams game. He is being offered to play in a balanced small teams game. If he declines, he will not be annoyed again. Polls in the room have been temporarily halted so he's not missing out on the votespam.

**Comment by Licho1** [comment]
This is impossible it constructs the games after people ready and not before.

**Comment by DeinFreund** [comment]
You're right. I removed the information about the queue, because the server doesn't know beforehand what queue is going to be ready.
