### ISSUE TITLE
!poll balance lacks vote buttons

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Chobby#632]
Why is this even a poll?

**Comment by ArchShaman** [comment]
![image](https://user-images.githubusercontent.com/7841201/44589276-f85dbf00-a76c-11e8-881a-a9f7e7f7bd31.png)

**Comment by Histidine91** [comment]
Every command has an autogenerated poll version IIRC. Although I dunno why the buttons aren't there.

**Comment by sprunk** [comment]
The protocol has no support for polls and everything is detecetd based on text parsing. This one does not seem to have `?` at the end.
