### ISSUE TITLE
Autohosts can be defaced

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Chobby#639]
Anyone is able to change the map on an autohost to any map. Please change the map automatically to a random featured or supported map after the room has been empty for 30 seconds if the current one is not already. Smurfs could still prevent that so the map could be changed anyway if there's no user activity after 5 minutes. Autohosts and Matchmaker battles are probably more official than other rooms.

**Comment by sprunk** [comment]
belongs to infra, chobby is just the GUI https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2404
