### ISSUE TITLE
Lobby links completely non-functional with steam browser

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#643]
Disabling the steam overlay disabled the lobby links. The option to use the steam browser should have been disabled. The default is broken.

**Comment by DeinFreund** [comment]
This also breaks the report button and might explain why we've been missing out on trolls/griefers.

**Comment by Licho1** [comment]
... i still haven't seen the regression people talked about which caused overlay to be disabled..
How real it was? For how many people?

**Comment by GoogleFrog** [comment]
Sounds like the overlay should be force-disabled again. Is there any way to add the friend popup to the lobby? Is there any way to detect whether the overlay is enabled @Licho1 ? If chobby can know whether the overlay can be enabled then it could force external browser and make a "manually invite via steam" information popup when the overlay is disabled.

**Comment by Licho1** [comment]
Yes wrapper knows if overlay is enabled and even active at given point.
It is also possible to 100% replicate steam functionality. We can show list of friends and send invite requests via game. @GoogleFrog
