### ISSUE TITLE
Chobby doesn't register !resetoptions' changes

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Chobby#66]

**Comment by GoogleFrog** [comment]
See https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1357

**Comment by Licho1** [comment]
It is relative to defaults not "last change".

**Comment by GoogleFrog** [comment]
It's not relative to defaults. I have tested, SetModOptions sends diffs from previous state or an empty table. The empty table is the only thing which is expected to be interpreted as relative to defaults.

I closed the ticket because I implemented the hacky behaviour in chobby.

**Comment by Licho1** [comment]
It is, that is the semantics of server protocol.
Relative to defaults. Of course, if you execute setoptions, it overrides previous changes. Its up to lobby gui to incorporate those in setoptions request.
Lobby server always sets setoptions based on the last setoptions command ignoring any previous commands.

**Comment by Licho1** [comment]
As in !setoptions does not add previous changes to it .. it just resends it, but all clients should understand those new setoptions as change from defaults, because thats what springie understands.

**Comment by GoogleFrog** [comment]
Already done.
