### ISSUE TITLE
Non-100% Lobby Interface Scale reduced FPS until reset

### ISSUE THREAD

**Issue by Porkch0p** [ZeroK-RTS/Chobby#680]
**Overview:**
When Lobby Interface Scale is set to 110%, the lobby is running at half the FPS of at 100% (90 vs 45 FPS). It happens when either scaling up or down.

If 'Lobby Interface Scale' is reset from 110% -> 100% -> 110%, the lobby is both scaled at 110% and running at no performance loss as long as the lobby stays running.

**To Replicate:**
You need a method to show FPS in the lobby. I used FRAPS. 'Expected' values show the result measured at 100% scale.

In Settings change 'Lobby Interface Scale' to 110. 

Restart Zero-K
> Expected FPS in Community, Chat, Friends, Settings, Downloads tabs [85,58,168,129,165]
> Observed FPS in Community, Chat, Friends, Settings, Downloads tabs [46,25,163,112,153]

In Settings change 'Lobby Interface Scale' to 100. 
Then change it back to 110.

> Expected FPS in Community, Chat, Friends, Settings, Downloads tabs [85,58,168,129,165]
> Observed FPS in Community, Chat, Friends, Settings, Downloads tabs [93,56,178,123,168]

Test Machine: Windows 7 64-bit , Core i5, Nvidia GTX 670

**Comment by Porkch0p** [comment]
CPU Usage Reduction following the above steps (4 cores, so 25% is a full core)
![CPU Usage Reduction](https://i.imgur.com/2NriePy.png)

**Comment by Porkch0p** [comment]
This effect is also super unkind to lower-end graphics cards (FPS at top left)
![32FPS and laggy mouse on load](https://i.imgur.com/BVpHDCc.jpg)
![84FPS after resetting](https://i.imgur.com/d3DHgFm.jpg)

**Comment by Licho1** [comment]
Wait a moment, is this the root cause? Its in widget:ViewResize which should not be called constantly.. was it causing loops?

**Comment by GoogleFrog** [comment]
Not loops, just an update each frame.
