### ISSUE TITLE
Block certain usernames from signing up

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Chobby#681]
Chobby should be made to prevent inappropriate names (eg: racial slurs in name) in order to cut down on moderator action requirement. There's no reason at all for names like "glownigger" or "JuanIsAFaggot" to be allowed to sign up to begin with. This could be done clientside since few people mod chobby to begin with. 

Prevention of such names going through signup would reduce the amount of moderator action required as most of these usernames end up getting renamed anyways by humans. A valid exception for whatever reason could be approved by moderators (via rename) instead of default allowing anything goes.

Of course, such filters will not catch every racially motivated name, but a basic filter to catch the worst would help a bit I think.

Provide a list of things that aren't acceptable and I'll see about making this a reality.

**Comment by Cat-Lady** [comment]
Just be sure to not overdone it. There is enough of places where you can't write "wristwatch" (wrisTWATch) without tripping auto-filter.

**Comment by Arch-Shaman** [comment]
Twat isn't what I'd be aiming to filter out. Things like "nigger", "faggot"
and so on. Things that basically get renamed as soon as they're seen.

**Comment by gajop** [comment]
Things like this should definitely be done on the server. Send a message denying registration of such nicknames. You could consider duplicating functionality on the client, but server <-> client communication is so fast, I don't think it's worth the effort.

**Comment by Arch-Shaman** [comment]
Moved to infra then.
