### ISSUE TITLE
Chobby did not download map for some mission on installation and when starting mission. Leading to crashes

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Chobby#69]
Map for missions are not included in initial chobby download 

e.g.

Chicken_Nuggets_V4 for Very easy chickens mission

allegedly these missions below also lacking pre-packaged map:

Sandbox
2v1

When you try to start these missions without maps chobby crashes leaving error:

Archive "[map name here]" not found.

**Comment by GoogleFrog** [comment]
Fixed.
