### ISSUE TITLE
Priority of sounds in lobby

### ISSUE THREAD

**Issue by Cat-Lady** [ZeroK-RTS/Chobby#696]
Some sounds - like getting a private message - are being send "live" when ZK lobby isn't the window/screen in focus. Hoever, more important things - like "nuke" sound of matchmaker match found - are silenced.

Fixable?

**Comment by GoogleFrog** [comment]
Works on windows as far as I recall.

**Comment by Cat-Lady** [comment]
Closing as part of housecleaning.
