### ISSUE TITLE
Chobby doesn't download proper engine version

### ISSUE THREAD

**Issue by Cat-Lady** [ZeroK-RTS/Chobby#698]
https://i.imgur.com/AQHbnvB.png

...appears on every ZK start. Standalone, non-steam version. Previous engine updates were happening without problems.

**Comment by GoogleFrog** [comment]
Works for me. Impart infolog_full.

**Comment by Cat-Lady** [comment]
Infolog:
https://zerobin.net/?f7238d6010695d31#yiaQu98lSNY4fl43fqcuL/w0DOCU1YLq/wGHcpaJuB0=

(github doesn't want to attach infolog giving unhelpful "something went very wrong" message).

**Comment by Cat-Lady** [comment]
turned out to be steam_engine config file having old version hardcoded in it godsknowwhy. Deleting it resulted in game trying to start with new engine instead, and failing, due to lack of it - still no automatic download, but at least putting the correct engine in expected directory (manually) fixed the issue. For now.

**Comment by GoogleFrog** [comment]
Are you using a standard steam install?

**Comment by Cat-Lady** [comment]
The most funny part is that I'm not using steam install at all - I just, sometimes, fire up steam (while still running Zero-K.exe manually, via mono, outside of steam) to play co-op campaign.

I have no idea how the file ended up in my ZK directory. Maybe it was somehow created when ZK successfully connected to Steam API.

**Comment by Licho1** [comment]
Don't use hacked versions.
The file exists if it was steam folder before created and updatedby steam.
Use either steam version or non steam, but not something in the middle.

**Comment by Cat-Lady** [comment]
The directory was never managed by steam in any way. It was installed as per instructions in itch.io page - correct packages installed, Zero-K.exe downloaded, then './mono Zero-K.exe' executed, downloading all the rest.

The only thing that steam have to do with my ZK install is that, sometimes, steam executable is run while ZK is running, and ZK connects to steam API for local co-op (I would happily kick out steam out of the equation for co-op, if it would be possible).

**Comment by GoogleFrog** [comment]
When you run ZK in such non-standard ways you may accidentally break things. The state of your install is too poorly known to continue in general, and you found a manual fix for yourself. Open an Infra ticket if you are able to reproduce the issue with a fresh and unmodified install (from itch if required) with exact steps to reproduce it.
