### ISSUE TITLE
Generating a room password

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Chobby#703]
As people appear to make private rooms without passwords, I would like to propose implementing an option to generate a host password. I suppose users have been kicked for entering rooms that were meant to be private.

**Comment by GoogleFrog** [comment]
This sounds like you are solving an issue too far downstream from its source. I predict that adding an option that says "automatically generate password" will do nothing. Figure out how to align the intentions of the hoster of a room with the intentions that other people think the host has.

**Comment by Licho1** [comment]
Yeah let it on people
