### ISSUE TITLE
Remove "zk:stable" check hax

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#71]
I don't know how to extract things like AIs list, game name and archive existence for rapid tags. There are some places in the code where the check gameName == "zk:stable" occurs which need to be replaced with some VFS.

**Comment by Licho1** [comment]
If you want, wrapper can transmit these data to chobby. You also need userid from wrapper. We should probably prepare some file/table with such things.

**Comment by GoogleFrog** [comment]
I consider a wrapper solution to be a workaround as well. It may be needed but don't do it now. Wait and see how this ticket goes: https://springrts.com/mantis/view.php?id=5419
