### ISSUE TITLE
Standard channels are joined twice, leading to double printing of the channel topic

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#715]
Chobby seems to manually try to join autojoin channels like #zk, #clan_XXX, #zktop20 and so on. This leads to a duplication of the channel topic on every login. Optimally Chobby should only try to join channels that it isn't already joined in after login.

**Comment by GoogleFrog** [comment]
How does Chobby know which channels are automatically joined? Why doesn't the server not send a duplicate channel message upon double joining a channel?

**Comment by DeinFreund** [comment]
Yeah this probably should be handled by the server.
