### ISSUE TITLE
Antialiasing = Off does not disable antialiasing

### ISSUE THREAD

**Issue by Porkch0p** [ZeroK-RTS/Chobby#756]
From testing on a machine with intel integrated graphics, the setting currently labeled "Off" appears to still have an antialiasing penalty ("Off" currently sets MSAALevel to 1)

Manually setting MSAALevel=0 via springsettings.cfg gave a major performance boost on a low end CPU (Intel G620). This makes me believe that '1' is doing some level of antialiasing that could be optionally disabled. The spring docs show 0 as the default value for MSAALevel.

EDIT: From the spring source, this is happening because non-zero MSAALevels are rounded up to the next even number.
So Antialiasing = Off is actually performing 2xMSAA

```
 /* Quick macro to make a number even, by
 * forcing the rightmost bit to 0.
 */https://github.com/ZeroK-RTS/Chobby/issues/465#issuecomment-618623775
#define make_even_number(n) 	((n) += ((n) & 0x1)?1:0) //! ~ceil
```

EDIT 2: MSAALevel appears to be set this way because of [this mantis ticket](https://springrts.com/mantis/view.php?id=5625) related to a flickering bug. That ticket was closed before the [anti-flicker fix](https://github.com/ZeroK-RTS/Chobby/issues/465#issuecomment-618623775) in Chobby was added. Maybe it's safe to re-enable MSAALevel=0 with that other fix in place?

Setting MSAALevel to 0 didn't appear to 'stick' in springsettings.cfg after the game was closed, but the FPS gains were roughly double in the early game by setting it in the config before starting ZK. 

![Screenshot at 2020-07-26 21-01-52](https://user-images.githubusercontent.com/49832728/88520654-18c5d200-cfb1-11ea-884c-785d45f2fd32.jpg)

![Screenshot at 2020-07-26 21-05-31](https://user-images.githubusercontent.com/49832728/88520666-1bc0c280-cfb1-11ea-8255-46526cd94bd7.jpg)

**Comment by GoogleFrog** [comment]
I recall MSAALevel=0 making the unit icons extremely ugly. I would want the game to not look absolutely terrible before such an easy way to set MSAALevel=0 is enabled.

**Comment by Porkch0p** [comment]
The corners of mex circles appear chopped off in MSAA 0x when zoomed out. Some images to compare
https://imgur.com/a/IPP0inN

**Comment by GoogleFrog** [comment]
I think the icons look terrible there. This is potentially fixable art-side, otherwise it could do with investigating in the engine. I think the engine is unlikely to pull any PR that fixes how icons look, since this would be a graphics thing.

**Comment by Porkch0p** [comment]
That's really odd, I had a hard time noticing any perceptible difference between the 0x and current 2x versions for most icons. Maybe imgur is compressing something. I can get some uncompressed files to compare just in case you can see a difference there. If not, well, the art is probably most important, and the idea can always be left on the shelf for a possible later date.

**Comment by Porkch0p** [comment]
[uncompressed replay shots](https://github.com/ZeroK-RTS/Chobby/files/4986546/uncompressed.zip)

**Comment by Porkch0p** [comment]
Hmm, I'm also seeing some noticeable gains on an Nvidia-based laptop in the campaign. After the pain of trying to test on Intel configurations, it's somewhat nice to see it's applicable across architectures. 

The main thing that brought on this thread of development is that MSAALevel auto-resets every time you run Zero-K. New minimal idea: is there a way to get that springsetting to stick around when changed (aside from repacking chobby)?

**Comment by Porkch0p** [comment]
Decided to look into why mexes are looking squashed when rendered without AA, and it appears to be related to how circles are drawn by the engine. When circles are rendered without AA, they appear to be always drawn minus a section at the 45 degree "corners".
![MSAA](https://user-images.githubusercontent.com/49832728/88879773-582a3380-d1e8-11ea-8475-cd95ae91b9ff.png)

**Comment by Porkch0p** [comment]
Spring changelogs for 104.x show definite intent to use the MSAA for line smoothing benefits, going so far as to remove the older line smoothing techniques previously available as SmoothPoints and SmoothLines. Looks like it's rather unnecessary to look into this anymore, so I'm gonna mark this closed.

If anyone does run into this later on looking for a performance tweak, forcing your video card's settings to run spring with AA off does in fact render the game without MSAA.
