### ISSUE TITLE
Implement new Queue order

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#772]
There are two new fields for the waiting list:
 * The `UpdateUserBattleStatus` message now contains an integer `QueueOrder`, when somebody is to be queued, the person with the highest queue order will be put in queue first, while the lowest queue order has highest priority to get in the battle.
 * The `BattleHeader` message now contains an integer `MaxEvenPlayers`. If the number of unspecced players in a room is below `MaxEvenPlayers` and is uneven, the person with the highest queue order is automatically put in the waiting list.

**Comment by GoogleFrog** [comment]
- I don't know what you mean about `QueueOrder`, as I don't consider people to be queued or unqueued. I did some experimenting and it seems like `QueueOrder` just increments by one for each new player that joins the player slot. It looks like I just have to sort by `QueueOrder` and use `MaxEvenPlayers` to put the divider in the correct position. I would have preferred if the server told the lobby when a player was queued or not.
- The `BattleHeader` message doesn't exist. I made a guess as to what to do.
