### ISSUE TITLE
Additional custom game modes in host menu

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#774]
![image](https://user-images.githubusercontent.com/1318249/98492416-e2744000-228b-11eb-810a-832a9f415596.png)

This menu could be larger, with things like Zero Wars, or even particular maps and modoptions that people wish to save as presets. To make these modes modular I would do the following:
- Each mode is a file in a particular directory, that chobby reads each time the host menu is opened.
- The file says which underlying game type the room should host (eg custom, 1v1, teams). It could default to Custom.
- The file can have a set map to play on and a list of modoptions commands to send when the host creates the room.

Chobby could deploy these files initially, and players could then edit them and trade them around. This would aid in discoverability for full mods, but would also let people save their modoptions and unittweaks.

**Comment by Licho1** [comment]
How will we map resources to these menu? Will there be special lua file inside mutator with information about the mode?

Btw dont forget I recently added steam workshop support. One can mod *anyuthing* in ZK, including chobby

**Comment by GoogleFrog** [comment]
The resources are not mapped, I just hope they exist.

The steam workshop is incomplete as I think you're the only one who knows how to put something on the steam workshop. The files I added for this ticket would be perfect candidates for the workshop. People can share combinations of maps and modoptions, not just mutators.

**Comment by Licho1** [comment]
There was a guide somewhere...
Its just put stuff into a folder, modify text file, run some program. Maybe I only put it to chat and waited for someone else to test it which didnt happen.. oh well..
