### ISSUE TITLE
Report messages split by "_"

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#781]
![image](https://user-images.githubusercontent.com/1318249/102484394-55a67880-40ba-11eb-91a4-193f3d7b24cb.png)

Player names can't be split by spaces, so perhaps use them for this message.

**Comment by sprunk** [comment]
Players names split by space technically exist http://zero-k.info/Users/Detail/350257

This isn't really a concern here (there's a handful of them, all unused for years) but perhaps it would be a good idea to run whatever check is used for usernames at the moment on all existing accounts (note that this one also contains the forbidden \` character, there are also accounts with #).

**Comment by GoogleFrog** [comment]
Chobby doesn't expect spaces in player names in various places.

**Comment by sprunk** [comment]
ZeroK-RTS/Zero-K@cf97f837cdb19dd2c660ebb8e7f17bf15723319e
