### ISSUE TITLE
Implement server-side game modes

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#783]
Implement the protocol changes - check against test environment.

Test by trying to start a game  mode you do not have locally using play this mod button from website.

**Comment by Arch-Shaman** [comment]
Will this include the ability for mod authors to update game mode things?

**Comment by Licho1** [comment]
Yes, this is already implemented in website. 
Check it out here: 
http://test.zero-k.info/Mods

**Comment by GoogleFrog** [comment]
Done https://github.com/ZeroK-RTS/Chobby/issues/789
