### ISSUE TITLE
Access violation on start up.

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Chobby#81]
[f=-000001] Error: LuaMenu::RunCallIn: error = 2, Initialize, [Internal Lua error: Call failure] error = 2, LuaHandler/handler.lua, error = 2, LuaMenu/config.lua, error = 3, LuaMenu/Config/IGL_data.lua, [string "LuaMenu/Config/IGL_data.lua"]:122: '<eof>' expected near '}'
stack traceback:
	[C]: in function 'Include'
	[string "LuaHandler/Utilities/utils.lua"]:123: in function 'include'
	[string "LuaMenu/main.lua"]:54: in main chunk

Full infolog here: http://pastebin.com/EdwizKT8

**Comment by ArchShaman** [comment]
http://pastebin.com/7Q9hEC4v this is the file this error complains about. Note there's an extra } at the end.

**Comment by GoogleFrog** [comment]
Engine fixed https://springrts.com/mantis/view.php?id=5429
