### ISSUE TITLE
Clan icons are missing

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Chobby#82]
Chobby seems to not download clan icons on a new install. 

Most clans ingame and in lobby have blank logos. The ones that do have icons have them from the times they were committed to ZK game repository directly.

Unsure if this should be done by chobby itself using http hack like with replays, or just done by wrapper on game start.

**Comment by GoogleFrog** [comment]
I think it should be done with the wrapper when it launches. Packaged installer would come with all clan images already in place and wrapper would just keep them up to date. Chobby is configured to use the same clan icon directory that ZKL populates for use ingame.

**Comment by Anarchid** [comment]
The wrapper has a function to download the image files since the referred wrapper ticket was resolved, but it seems that Chobby lua never asks for those files.

**Comment by GoogleFrog** [comment]
See my comment. If the clan icons exist then they are displayed. I have not looked into other methods.

**Comment by Anarchid** [comment]
Current images that exist are either legacy from ZKL or are [5  years old](https://github.com/ZeroK-RTS/Zero-K/tree/master/LuaUI/Configs/Clans).

I decided to check how ZKL handled this and [found](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/5ddec86591302bf858ac6c2f1e362a46952f0235/ZeroKLobby/ServerImagesHandler.cs#L66) that ZKL downloaded each clan icon it encounted if it the file older than three days on the disk. 

Chobby has no way to check file write dates that i know of, and the wrapper download function does not run the three days check. However, the ZKL solution seems to amount to downloading every clan pic every three days, which is "doable".

It probably makes sense to get rid of clan images in the game repo.

**Comment by Licho1** [comment]
Clan pictures can be part of steam update which can happen for example each day (even with no changes to game)

**Comment by Anarchid** [comment]
I think it would be cleaner if this does not require Steam updates and works without Steam if necessary. I'd go with the wrapper implementing a ZKL-like solution, but using HTTPRequest instead of WebClient so that it can use `If-Modified-Since`.

**Comment by Licho1** [comment]
Bump, there is interface to do it in wrapper, lobby should download images that are missing.

**Comment by GoogleFrog** [comment]
How does the lobby know what is missing?

**Comment by Licho1** [comment]
It knows clan and avatar of people, it is sent in "user" it can check if the file is in vfs or not.

**Comment by GoogleFrog** [comment]
Ok. So if a clan or avatar image is not found it should request the image? Presumably it should only request once per session or a failed image could spam the downloads.

**Comment by Anarchid** [comment]
You could just re-download the whole deal every three days or so (by remembering the last time it was done). That's how ZKL used to do it in practice.

It could be possible to change the downloader function to use if-modified-since to actually only download the ones changed on server.

**Comment by Licho1** [comment]
Yes, i dont think we should allow image change without name change, then there is no need for re-requests.

**Comment by GoogleFrog** [comment]
Done https://github.com/ZeroK-RTS/Chobby/commit/c29350302393fd6bc58b1a1b88060eac5c83891e
