### ISSUE TITLE
Chobby Cannot access replays

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Chobby#847]
Replication:
1.) http://zero-k.info/Battles/Detail/1590532 click watch replay now
2.) Lobby reports cannot download
3.) Manual download still works.

Different from https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2939 (which probably should be closed after "rehydration")

**Comment by GoogleFrog** [comment]
Works for me. I clicked the button on site and got the replay. It worked right after steam update, I hadn't done any development or testing on this install.

**Comment by Arch-Shaman** [comment]
Tested today, seems to be working now. Closing issue as no additional work is needed.
