### ISSUE TITLE
ZK soft-crashes when opening forum links from Chobby

### ISSUE THREAD

**Issue by adams164** [ZeroK-RTS/Chobby#851]
Under a certain set of circumstances, ZK will soft-crash when opening forum links from Chobby.
To reproduce:
0. Disable "steam browser"
1. Set menu display mode to borderless window
2. Close, then reopen ZK
3. Open link from from welcome page
4. ZK now soft-crashed

**Comment by GoogleFrog** [comment]
What do you mean by "soft-crashed"? What happens for me is that ZK minimises and can't come back.
