### ISSUE TITLE
Manual !split?

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#875]
It would be possible to make a !split command that causes everyone in the battleroom to move to a new room. It wouldn't even be that hard.
- The command would have to send the name of another autohost, and the elo threshold, so that clients agree.
- The sender could just type !split and their lobby could figure out the elo and identity of the autohost to move to.
- Clients could be made to not show the room they did not end up in, unless their room falls below a player threshold.
- This would have to work on a whitelist of players that are allowed to send !split commands. Moderators could be whitelist, but technically anyone could be. The big question is who we would trust with this though.

**Comment by GoogleFrog** [comment]
- Consider letting everyone do it, but only for really large games (40 players?).
- Consider giving more players to the low elo game, to help it along.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2803 linking infra pot ticket.
