### ISSUE TITLE
Consider making split avoid two odd-sized games

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Chobby#877]
Lobpot with 42 people just got split into 25 and 17. Perhaps it would be good to move one person in any direction in such case (26+16 or 24+18) so it makes two even games instead of two odd.

**Comment by GoogleFrog** [comment]
Not sure. It seems reasonably likely that one of the split spectators will join the game, or someone will leave. So the exact split being odd or even does not seem that relevant.

**Comment by sprunk** [comment]
It turned out the 25 room became 22 by the time the game started so it seems volatile enough.
