### ISSUE TITLE
Split may be unspeccing the pros

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Chobby#880]
Aquanim says that he gets unspecced when being moved. Likely being moved resets your room status. In that case it would only affect the pros in the higher room since afaik they are always the ones to move into a new room. Might also explain some portion of room death (afkers who were supposed to spec cause exits).

**Comment by GoogleFrog** [comment]
That's not surprising. I guess chobby has to remember its state and set the new one in the new room appropriately.
