### ISSUE TITLE
Reword the split "no coming back" message

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Chobby#883]
![image](https://github.com/ZeroK-RTS/Chobby/assets/2573076/2f44cbae-28fd-4ec8-90ba-59c957dd6a3a)
This sounds as if you can't play in any room other than #2 (feels bad being forced to do something specific). But actually you just can't go back to #1.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Chobby/commit/b65781f584a093657b089ce9138b0ddb2c07a42c
