### ISSUE TITLE
Heading art required.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#96]
The heading up the top left of the screen now has the purpose of telling players which submenu they are in. The current images are placeholders. Some nice small and large versions are required for Singleplayer, Multiplayer, Campaign and Help. Also Help might want to be renamed to Extras.

![ivorychanges](https://cloud.githubusercontent.com/assets/1318249/22286422/2b484c86-e343-11e6-8fbd-871c1ea5fa51.jpg)

**Comment by Anarchid** [comment]
> Some nice small and large versions 

What are the sizes? Do you want just fonts, or fonts with effects, or fonts with icons, or fonts with some other kind of theming (backgrounds?)
